import { Emoji, IEmoji } from '../models/Emoji';
export const emojisDefault: IEmoji[] = [
new Emoji("😀", "Peoples", ['grinning', 'grinning_face']),
new Emoji("😃", "Peoples", ['grinning_face_with_big_eyes', 'smiley']),
new Emoji("😄", "Peoples", ['grinning_face_with_closed_eyes', 'smile']),
new Emoji("😁", "Peoples", ['beaming_face', 'grin']),
new Emoji("😆", "Peoples", ['laughing', 'lol', 'satisfied', 'squinting_face']),
new Emoji("😅", "Peoples", ['grinning_face_with_sweat', 'sweat_smile']),
new Emoji("🤣", "Peoples", ['rofl']),
new Emoji("😂", "Peoples", ['joy', 'lmao', 'tears_of_joy']),
new Emoji("🙂", "Peoples", ['slightly_smiling_face']),
new Emoji("🙃", "Peoples", ['upside_down_face']),
new Emoji("🫠", "Peoples", ['melt', 'melting_face']),
new Emoji("😉", "Peoples", ['wink', 'winking_face']),
new Emoji("😊", "Peoples", ['blush', 'smiling_face_with_closed_eyes']),
new Emoji("😇", "Peoples", ['halo', 'innocent']),
new Emoji("🥰", "Peoples", ['smiling_face_with_3_hearts']),
new Emoji("😍", "Peoples", ['heart_eyes', 'smiling_face_with_heart_eyes']),
new Emoji("🤩", "Peoples", ['star_struck']),
new Emoji("😘", "Peoples", ['blowing_a_kiss', 'kissing_heart']),
new Emoji("😗", "Peoples", ['kissing', 'kissing_face']),
new Emoji("☺️", "Peoples", ['relaxed', 'smiling_face']),
new Emoji("😚", "Peoples", ['kissing_closed_eyes', 'kissing_face_with_closed_eyes']),
new Emoji("😙", "Peoples", ['kissing_face_with_smiling_eyes', 'kissing_smiling_eyes']),
new Emoji("🥲", "Peoples", ['smiling_face_with_tear']),
new Emoji("😋", "Peoples", ['savoring_food', 'yum']),
new Emoji("😛", "Peoples", ['face_with_tongue', 'stuck_out_tongue']),
new Emoji("😜", "Peoples", ['stuck_out_tongue_winking_eye']),
new Emoji("🤪", "Peoples", ['zany', 'zany_face']),
new Emoji("😝", "Peoples", ['stuck_out_tongue_closed_eyes']),
new Emoji("🤑", "Peoples", ['money_mouth_face']),
new Emoji("🤗", "Peoples", ['hug', 'hugging', 'hugging_face']),
new Emoji("🤭", "Peoples", ['face_with_hand_over_mouth', 'hand_over_mouth']),
new Emoji("🫢", "Peoples", ['face_with_open_eyes_hand_over_mouth', 'gasp']),
new Emoji("🫣", "Peoples", ['face_with_peeking_eye', 'peek']),
new Emoji("🤫", "Peoples", ['shush', 'shushing_face']),
new Emoji("🤔", "Peoples", ['thinking', 'thinking_face', 'wtf']),
new Emoji("🫡", "Peoples", ['salute', 'saluting_face']),
new Emoji("🤐", "Peoples", ['zipper_mouth', 'zipper_mouth_face']),
new Emoji("🤨", "Peoples", ['face_with_raised_eyebrow', 'raised_eyebrow']),
new Emoji("😐️", "Peoples", ['neutral', 'neutral_face']),
new Emoji("😑", "Peoples", ['expressionless', 'expressionless_face']),
new Emoji("😶", "Peoples", ['no_mouth']),
new Emoji("🫥", "Peoples", ['dotted_line_face']),
new Emoji("😶‍🌫️", "Peoples", ['in_clouds']),
new Emoji("😏", "Peoples", ['smirk', 'smirking', 'smirking_face']),
new Emoji("😒", "Peoples", ['unamused', 'unamused_face']),
new Emoji("🙄", "Peoples", ['rolling_eyes']),
new Emoji("😬", "Peoples", ['grimacing', 'grimacing_face']),
new Emoji("😮‍💨", "Peoples", ['exhale', 'exhaling']),
new Emoji("🤥", "Peoples", ['lying', 'lying_face']),
new Emoji("😌", "Peoples", ['relieved', 'relieved_face']),
new Emoji("😔", "Peoples", ['pensive', 'pensive_face']),
new Emoji("😪", "Peoples", ['sleepy', 'sleepy_face']),
new Emoji("🤤", "Peoples", ['drooling', 'drooling_face']),
new Emoji("😴", "Peoples", ['sleeping', 'sleeping_face']),
new Emoji("😷", "Peoples", ['mask', 'medical_mask']),
new Emoji("🤒", "Peoples", ['face_with_thermometer']),
new Emoji("🤕", "Peoples", ['face_with_head_bandage']),
new Emoji("🤢", "Peoples", ['nauseated', 'nauseated_face']),
new Emoji("🤮", "Peoples", ['face_vomiting', 'vomiting']),
new Emoji("🤧", "Peoples", ['sneezing', 'sneezing_face']),
new Emoji("🥵", "Peoples", ['hot', 'hot_face']),
new Emoji("🥶", "Peoples", ['cold', 'cold_face']),
new Emoji("🥴", "Peoples", ['woozy', 'woozy_face']),
new Emoji("😵", "Peoples", ['dizzy_face', 'knocked_out']),
new Emoji("😵‍💫", "Peoples", ['dizzy_eyes']),
new Emoji("🤯", "Peoples", ['exploding_head']),
new Emoji("🤠", "Peoples", ['cowboy', 'cowboy_face']),
new Emoji("🥳", "Peoples", ['hooray', 'partying', 'partying_face']),
new Emoji("🥸", "Peoples", ['disguised', 'disguised_face']),
new Emoji("😎", "Peoples", ['smiling_face_with_sunglasses', 'sunglasses_cool', 'too_cool']),
new Emoji("🤓", "Peoples", ['nerd', 'nerd_face']),
new Emoji("🧐", "Peoples", ['face_with_monocle']),
new Emoji("😕", "Peoples", ['confused', 'confused_face']),
new Emoji("🫤", "Peoples", ['face_with_diagonal_mouth']),
new Emoji("😟", "Peoples", ['worried', 'worried_face']),
new Emoji("🙁", "Peoples", ['slightly_frowning_face']),
new Emoji("☹️", "Peoples", ['white_frowning_face']),
new Emoji("😮", "Peoples", ['face_with_open_mouth', 'open_mouth']),
new Emoji("😯", "Peoples", ['hushed', 'hushed_face']),
new Emoji("😲", "Peoples", ['astonished', 'astonished_face']),
new Emoji("😳", "Peoples", ['flushed', 'flushed_face']),
new Emoji("🥺", "Peoples", ['pleading', 'pleading_face']),
new Emoji("🥹", "Peoples", ['face_holding_back_tears', 'watery_eyes']),
new Emoji("😦", "Peoples", ['frowning', 'frowning_face']),
new Emoji("😧", "Peoples", ['anguished', 'anguished_face']),
new Emoji("😨", "Peoples", ['fearful', 'fearful_face']),
new Emoji("😰", "Peoples", ['anxious', 'anxious_face', 'cold_sweat']),
new Emoji("😥", "Peoples", ['disappointed_relieved', 'sad_relieved_face']),
new Emoji("😢", "Peoples", ['cry', 'crying_face']),
new Emoji("😭", "Peoples", ['loudly_crying_face', 'sob']),
new Emoji("😱", "Peoples", ['scream', 'screaming_in_fear']),
new Emoji("😖", "Peoples", ['confounded', 'confounded_face']),
new Emoji("😣", "Peoples", ['persevere', 'persevering_face']),
new Emoji("😞", "Peoples", ['disappointed', 'disappointed_face']),
new Emoji("😓", "Peoples", ['downcast_face', 'sweat']),
new Emoji("😩", "Peoples", ['weary', 'weary_face']),
new Emoji("😫", "Peoples", ['tired', 'tired_face']),
new Emoji("🥱", "Peoples", ['yawn', 'yawning', 'yawning_face']),
new Emoji("😤", "Peoples", ['nose_steam', 'triumph']),
new Emoji("😡", "Peoples", ['pout', 'pouting_face', 'rage']),
new Emoji("😠", "Peoples", ['angry', 'angry_face']),
new Emoji("🤬", "Peoples", ['censored', 'face_with_symbols_on_mouth']),
new Emoji("😈", "Peoples", ['smiling_imp']),
new Emoji("👿", "Peoples", ['angry_imp', 'imp']),
new Emoji("💀", "Peoples", ['skull']),
new Emoji("☠️", "Peoples", ['skull_and_crossbones']),
new Emoji("💩", "Peoples", ['poop', 'shit']),
new Emoji("🤡", "Peoples", ['clown', 'clown_face']),
new Emoji("👹", "Peoples", ['japanese_ogre', 'ogre']),
new Emoji("👺", "Peoples", ['goblin', 'japanese_goblin']),
new Emoji("👻", "Peoples", ['ghost']),
new Emoji("👽️", "Peoples", ['alien']),
new Emoji("👾", "Peoples", ['alien_monster', 'space_invader']),
new Emoji("🤖", "Peoples", ['robot', 'robot_face']),
new Emoji("😺", "Peoples", ['grinning_cat', 'smiley_cat']),
new Emoji("😸", "Peoples", ['grinning_cat_with_closed_eyes', 'smile_cat']),
new Emoji("😹", "Peoples", ['joy_cat', 'tears_of_joy_cat']),
new Emoji("😻", "Peoples", ['heart_eyes_cat', 'smiling_cat_with_heart_eyes']),
new Emoji("😼", "Peoples", ['smirk_cat', 'wry_smile_cat']),
new Emoji("😽", "Peoples", ['kissing_cat']),
new Emoji("🙀", "Peoples", ['scream_cat', 'weary_cat']),
new Emoji("😿", "Peoples", ['crying_cat']),
new Emoji("😾", "Peoples", ['pouting_cat']),
new Emoji("🙈", "Peoples", ['see_no_evil']),
new Emoji("🙉", "Peoples", ['hear_no_evil']),
new Emoji("🙊", "Peoples", ['speak_no_evil']),
new Emoji("💋", "Peoples", ['kiss']),
new Emoji("💌", "Peoples", ['love_letter']),
new Emoji("💘", "Peoples", ['cupid', 'heart_with_arrow']),
new Emoji("💝", "Peoples", ['gift_heart', 'heart_with_ribbon']),
new Emoji("💖", "Peoples", ['sparkling_heart']),
new Emoji("💗", "Peoples", ['growing_heart', 'heartpulse']),
new Emoji("💓", "Peoples", ['beating_heart', 'heartbeat']),
new Emoji("💞", "Peoples", ['revolving_hearts']),
new Emoji("💕", "Peoples", ['two_hearts']),
new Emoji("💟", "Peoples", ['heart_decoration']),
new Emoji("❣️", "Peoples", ['heart_exclamation']),
new Emoji("💔", "Peoples", ['broken_heart']),
new Emoji("❤️‍🔥", "Peoples", ['heart_on_fire']),
new Emoji("❤️‍🩹", "Peoples", ['mending_heart']),
new Emoji("❤️", "Peoples", ['heart', 'red_heart']),
new Emoji("🧡", "Peoples", ['orange_heart']),
new Emoji("💛", "Peoples", ['yellow_heart']),
new Emoji("💚", "Peoples", ['green_heart']),
new Emoji("💙", "Peoples", ['blue_heart']),
new Emoji("💜", "Peoples", ['purple_heart']),
new Emoji("🤎", "Peoples", ['brown_heart']),
new Emoji("🖤", "Peoples", ['black_heart']),
new Emoji("🤍", "Peoples", ['white_heart']),
new Emoji("💯", "Peoples", ['100']),
new Emoji("💢", "Peoples", ['anger']),
new Emoji("💥", "Peoples", ['boom', 'collision']),
new Emoji("💫", "Peoples", ['dizzy']),
new Emoji("💦", "Peoples", ['sweat_drops']),
new Emoji("💨", "Peoples", ['dash', 'dashing_away']),
new Emoji("🕳️", "Peoples", ['hole']),
new Emoji("💣️", "Peoples", ['bomb']),
new Emoji("💬", "Peoples", ['speech_balloon']),
new Emoji("👁️‍🗨️", "Peoples", ['eye_in_speech_bubble']),
new Emoji("🗨️", "Peoples", ['left_speech_bubble']),
new Emoji("🗯️", "Peoples", ['right_anger_bubble']),
new Emoji("💭", "Peoples", ['thought_balloon']),
new Emoji("💤", "Peoples", ['zzz']),
new Emoji("👋", "Peoples", ['wave', 'waving_hand']),
new Emoji("🤚", "Peoples", ['raised_back_of_hand']),
new Emoji("🖐️", "Peoples", ['raised_hand_with_fingers_splayed']),
new Emoji("✋", "Peoples", ['high_five', 'raised_hand']),
new Emoji("🖖", "Peoples", ['vulcan']),
new Emoji("🫱", "Peoples", ['rightwards_hand']),
new Emoji("🫲", "Peoples", ['leftwards_hand']),
new Emoji("🫳", "Peoples", ['palm_down']),
new Emoji("🫴", "Peoples", ['palm_up']),
new Emoji("👌", "Peoples", ['ok_hand']),
new Emoji("🤌", "Peoples", ['pinch', 'pinched_fingers']),
new Emoji("🤏", "Peoples", ['pinching_hand']),
new Emoji("✌️", "Peoples", ['v', 'victory']),
new Emoji("🤞", "Peoples", ['fingers_crossed']),
new Emoji("🫰", "Peoples", ['hand_with_index_finger_and_thumb_crossed']),
new Emoji("🤟", "Peoples", ['love_you_gesture']),
new Emoji("🤘", "Peoples", ['metal', 'sign_of_the_horns']),
new Emoji("🤙", "Peoples", ['call_me_hand']),
new Emoji("👈️", "Peoples", ['point_left']),
new Emoji("👉️", "Peoples", ['point_right']),
new Emoji("👆️", "Peoples", ['point_up']),
new Emoji("🖕", "Peoples", ['middle_finger']),
new Emoji("👇️", "Peoples", ['point_down']),
new Emoji("☝️", "Peoples", ['point_up_2']),
new Emoji("🫵", "Peoples", ['point_forward']),
new Emoji("👍️", "Peoples", ['+1', 'thumbsup', 'yes']),
new Emoji("👎️", "Peoples", ['-1', 'no', 'thumbsdown']),
new Emoji("✊", "Peoples", ['fist']),
new Emoji("👊", "Peoples", ['punch']),
new Emoji("🤛", "Peoples", ['left_facing_fist']),
new Emoji("🤜", "Peoples", ['right_facing_fist']),
new Emoji("👏", "Peoples", ['clap', 'clapping_hands']),
new Emoji("🙌", "Peoples", ['raised_hands']),
new Emoji("🫶", "Peoples", ['heart_hands']),
new Emoji("👐", "Peoples", ['open_hands']),
new Emoji("🤲", "Peoples", ['palms_up_together']),
new Emoji("🤝", "Peoples", ['handshake']),
new Emoji("🙏", "Peoples", ['folded_hands', 'pray']),
new Emoji("✍️", "Peoples", ['writing_hand']),
new Emoji("💅", "Peoples", ['nail_care', 'nail_polish']),
new Emoji("🤳", "Peoples", ['selfie']),
new Emoji("💪", "Peoples", ['muscle', 'right_bicep']),
new Emoji("🦾", "Peoples", ['mechanical_arm']),
new Emoji("🦿", "Peoples", ['mechanical_leg']),
new Emoji("🦵", "Peoples", ['leg']),
new Emoji("🦶", "Peoples", ['foot']),
new Emoji("👂️", "Peoples", ['ear']),
new Emoji("🦻", "Peoples", ['ear_with_hearing_aid', 'hearing_aid']),
new Emoji("👃", "Peoples", ['nose']),
new Emoji("🧠", "Peoples", ['brain']),
new Emoji("🫀", "Peoples", ['anatomical_heart']),
new Emoji("🫁", "Peoples", ['lungs']),
new Emoji("🦷", "Peoples", ['tooth']),
new Emoji("🦴", "Peoples", ['bone']),
new Emoji("👀", "Peoples", ['eyes']),
new Emoji("👁️", "Peoples", ['eye']),
new Emoji("👅", "Peoples", ['tongue']),
new Emoji("👄", "Peoples", ['lips', 'mouth']),
new Emoji("🫦", "Peoples", ['biting_lip']),
new Emoji("👶", "Peoples", ['baby']),
new Emoji("🧒", "Peoples", ['child']),
new Emoji("👦", "Peoples", ['boy']),
new Emoji("👧", "Peoples", ['girl']),
new Emoji("🧑", "Peoples", ['adult']),
new Emoji("👱", "Peoples", ['blond_haired']),
new Emoji("👨", "Peoples", ['man']),
new Emoji("🧔", "Peoples", ['person_bearded']),
new Emoji("🧔‍♂️", "Peoples", ['man_bearded']),
new Emoji("🧔‍♀️", "Peoples", ['woman_bearded']),
new Emoji("👨‍🦰", "Peoples", ['man_red_haired']),
new Emoji("👨‍🦱", "Peoples", ['man_curly_haired']),
new Emoji("👨‍🦳", "Peoples", ['man_white_haired']),
new Emoji("👨‍🦲", "Peoples", ['man_bald']),
new Emoji("👩", "Peoples", ['woman']),
new Emoji("👩‍🦰", "Peoples", ['woman_red_haired']),
new Emoji("🧑‍🦰", "Peoples", ['red_haired']),
new Emoji("👩‍🦱", "Peoples", ['woman_curly_haired']),
new Emoji("🧑‍🦱", "Peoples", ['curly_haired']),
new Emoji("👩‍🦳", "Peoples", ['woman_white_haired']),
new Emoji("🧑‍🦳", "Peoples", ['white_haired']),
new Emoji("👩‍🦲", "Peoples", ['woman_bald']),
new Emoji("🧑‍🦲", "Peoples", ['bald']),
new Emoji("👱‍♀️", "Peoples", ['woman_blond_haired']),
new Emoji("👱‍♂️", "Peoples", ['man_blond_haired']),
new Emoji("🧓", "Peoples", ['older_adult']),
new Emoji("👴", "Peoples", ['older_man']),
new Emoji("👵", "Peoples", ['older_woman']),
new Emoji("🙍", "Peoples", ['person_frowning']),
new Emoji("🙍‍♂️", "Peoples", ['man_frowning']),
new Emoji("🙍‍♀️", "Peoples", ['woman_frowning']),
new Emoji("🙎", "Peoples", ['person_pouting', 'pouting']),
new Emoji("🙎‍♂️", "Peoples", ['man_pouting']),
new Emoji("🙎‍♀️", "Peoples", ['woman_pouting']),
new Emoji("🙅", "Peoples", ['no_good', 'person_gesturing_no']),
new Emoji("🙅‍♂️", "Peoples", ['man_gesturing_no']),
new Emoji("🙅‍♀️", "Peoples", ['woman_gesturing_no']),
new Emoji("🙆", "Peoples", ['all_good', 'person_gesturing_ok']),
new Emoji("🙆‍♂️", "Peoples", ['man_gesturing_ok']),
new Emoji("🙆‍♀️", "Peoples", ['woman_gesturing_ok']),
new Emoji("💁", "Peoples", ['person_tipping_hand']),
new Emoji("💁‍♂️", "Peoples", ['man_tipping_hand']),
new Emoji("💁‍♀️", "Peoples", ['woman_tipping_hand']),
new Emoji("🙋", "Peoples", ['person_raising_hand']),
new Emoji("🙋‍♂️", "Peoples", ['man_raising_hand']),
new Emoji("🙋‍♀️", "Peoples", ['woman_raising_hand']),
new Emoji("🧏", "Peoples", ['deaf_person']),
new Emoji("🧏‍♂️", "Peoples", ['deaf_man']),
new Emoji("🧏‍♀️", "Peoples", ['deaf_woman']),
new Emoji("🙇", "Peoples", ['bow', 'person_bowing']),
new Emoji("🙇‍♂️", "Peoples", ['man_bowing']),
new Emoji("🙇‍♀️", "Peoples", ['woman_bowing']),
new Emoji("🤦", "Peoples", ['facepalm', 'person_facepalming']),
new Emoji("🤦‍♂️", "Peoples", ['man_facepalming']),
new Emoji("🤦‍♀️", "Peoples", ['woman_facepalming']),
new Emoji("🤷", "Peoples", ['person_shrugging', 'shrug']),
new Emoji("🤷‍♂️", "Peoples", ['man_shrugging']),
new Emoji("🤷‍♀️", "Peoples", ['woman_shrugging']),
new Emoji("🧑‍⚕️", "Peoples", ['health_worker']),
new Emoji("👨‍⚕️", "Peoples", ['man_health_worker']),
new Emoji("👩‍⚕️", "Peoples", ['woman_health_worker']),
new Emoji("🧑‍🎓", "Peoples", ['student']),
new Emoji("👨‍🎓", "Peoples", ['man_student']),
new Emoji("👩‍🎓", "Peoples", ['woman_student']),
new Emoji("🧑‍🏫", "Peoples", ['teacher']),
new Emoji("👨‍🏫", "Peoples", ['man_teacher']),
new Emoji("👩‍🏫", "Peoples", ['woman_teacher']),
new Emoji("🧑‍⚖️", "Peoples", ['judge']),
new Emoji("👨‍⚖️", "Peoples", ['man_judge']),
new Emoji("👩‍⚖️", "Peoples", ['woman_judge']),
new Emoji("🧑‍🌾", "Peoples", ['farmer']),
new Emoji("👨‍🌾", "Peoples", ['man_farmer']),
new Emoji("👩‍🌾", "Peoples", ['woman_farmer']),
new Emoji("🧑‍🍳", "Peoples", ['cook']),
new Emoji("👨‍🍳", "Peoples", ['man_cook']),
new Emoji("👩‍🍳", "Peoples", ['woman_cook']),
new Emoji("🧑‍🔧", "Peoples", ['mechanic']),
new Emoji("👨‍🔧", "Peoples", ['man_mechanic']),
new Emoji("👩‍🔧", "Peoples", ['woman_mechanic']),
new Emoji("🧑‍🏭", "Peoples", ['factory_worker']),
new Emoji("👨‍🏭", "Peoples", ['man_factory_worker']),
new Emoji("👩‍🏭", "Peoples", ['woman_factory_worker']),
new Emoji("🧑‍💼", "Peoples", ['office_worker']),
new Emoji("👨‍💼", "Peoples", ['man_office_worker']),
new Emoji("👩‍💼", "Peoples", ['woman_office_worker']),
new Emoji("🧑‍🔬", "Peoples", ['scientist']),
new Emoji("👨‍🔬", "Peoples", ['man_scientist']),
new Emoji("👩‍🔬", "Peoples", ['woman_scientist']),
new Emoji("🧑‍💻", "Peoples", ['technologist']),
new Emoji("👨‍💻", "Peoples", ['man_technologist']),
new Emoji("👩‍💻", "Peoples", ['woman_technologist']),
new Emoji("🧑‍🎤", "Peoples", ['singer']),
new Emoji("👨‍🎤", "Peoples", ['man_singer']),
new Emoji("👩‍🎤", "Peoples", ['woman_singer']),
new Emoji("🧑‍🎨", "Peoples", ['artist']),
new Emoji("👨‍🎨", "Peoples", ['man_artist']),
new Emoji("👩‍🎨", "Peoples", ['woman_artist']),
new Emoji("🧑‍✈️", "Peoples", ['pilot']),
new Emoji("👨‍✈️", "Peoples", ['man_pilot']),
new Emoji("👩‍✈️", "Peoples", ['woman_pilot']),
new Emoji("🧑‍🚀", "Peoples", ['astronaut']),
new Emoji("👨‍🚀", "Peoples", ['man_astronaut']),
new Emoji("👩‍🚀", "Peoples", ['woman_astronaut']),
new Emoji("🧑‍🚒", "Peoples", ['firefighter']),
new Emoji("👨‍🚒", "Peoples", ['man_firefighter']),
new Emoji("👩‍🚒", "Peoples", ['woman_firefighter']),
new Emoji("👮", "Peoples", ['cop', 'police_officer']),
new Emoji("👮‍♂️", "Peoples", ['man_police_officer']),
new Emoji("👮‍♀️", "Peoples", ['woman_police_officer']),
new Emoji("🕵️", "Peoples", ['detective']),
new Emoji("🕵️‍♂️", "Peoples", ['man_detective']),
new Emoji("🕵️‍♀️", "Peoples", ['woman_detective']),
new Emoji("💂", "Peoples", ['guard']),
new Emoji("💂‍♂️", "Peoples", ['man_guard']),
new Emoji("💂‍♀️", "Peoples", ['woman_guard']),
new Emoji("🥷", "Peoples", ['ninja']),
new Emoji("👷", "Peoples", ['construction_worker']),
new Emoji("👷‍♂️", "Peoples", ['man_construction_worker']),
new Emoji("👷‍♀️", "Peoples", ['woman_construction_worker']),
new Emoji("🫅", "Peoples", ['person_with_crown', 'royalty']),
new Emoji("🤴", "Peoples", ['prince']),
new Emoji("👸", "Peoples", ['princess']),
new Emoji("👳", "Peoples", ['person_wearing_turban']),
new Emoji("👳‍♂️", "Peoples", ['man_wearing_turban']),
new Emoji("👳‍♀️", "Peoples", ['woman_wearing_turban']),
new Emoji("👲", "Peoples", ['person_with_skullcap']),
new Emoji("🧕", "Peoples", ['woman_with_headscarf']),
new Emoji("🤵", "Peoples", ['person_in_tuxedo']),
new Emoji("🤵‍♂️", "Peoples", ['man_in_tuxedo']),
new Emoji("🤵‍♀️", "Peoples", ['woman_in_tuxedo']),
new Emoji("👰", "Peoples", ['person_with_veil']),
new Emoji("👰‍♂️", "Peoples", ['man_with_veil']),
new Emoji("👰‍♀️", "Peoples", ['woman_with_veil']),
new Emoji("🤰", "Peoples", ['pregnant_woman']),
new Emoji("🫃", "Peoples", ['pregnant_man']),
new Emoji("🫄", "Peoples", ['pregnant_person']),
new Emoji("🤱", "Peoples", ['breast_feeding']),
new Emoji("👩‍🍼", "Peoples", ['woman_feeding_baby']),
new Emoji("👨‍🍼", "Peoples", ['man_feeding_baby']),
new Emoji("🧑‍🍼", "Peoples", ['person_feeding_baby']),
new Emoji("👼", "Peoples", ['angel']),
new Emoji("🎅", "Peoples", ['santa']),
new Emoji("🤶", "Peoples", ['mrs_claus']),
new Emoji("🧑‍🎄", "Peoples", ['mx_claus']),
new Emoji("🦸", "Peoples", ['superhero']),
new Emoji("🦸‍♂️", "Peoples", ['man_superhero']),
new Emoji("🦸‍♀️", "Peoples", ['woman_superhero']),
new Emoji("🦹", "Peoples", ['supervillain']),
new Emoji("🦹‍♂️", "Peoples", ['man_supervillain']),
new Emoji("🦹‍♀️", "Peoples", ['woman_supervillain']),
new Emoji("🧙", "Peoples", ['mage']),
new Emoji("🧙‍♂️", "Peoples", ['man_mage']),
new Emoji("🧙‍♀️", "Peoples", ['woman_mage']),
new Emoji("🧚", "Peoples", ['fairy']),
new Emoji("🧚‍♂️", "Peoples", ['man_fairy']),
new Emoji("🧚‍♀️", "Peoples", ['woman_fairy']),
new Emoji("🧛", "Peoples", ['vampire']),
new Emoji("🧛‍♂️", "Peoples", ['man_vampire']),
new Emoji("🧛‍♀️", "Peoples", ['woman_vampire']),
new Emoji("🧜", "Peoples", ['merperson']),
new Emoji("🧜‍♂️", "Peoples", ['merman']),
new Emoji("🧜‍♀️", "Peoples", ['mermaid']),
new Emoji("🧝", "Peoples", ['elf']),
new Emoji("🧝‍♂️", "Peoples", ['man_elf']),
new Emoji("🧝‍♀️", "Peoples", ['woman_elf']),
new Emoji("🧞", "Peoples", ['genie']),
new Emoji("🧞‍♂️", "Peoples", ['man_genie']),
new Emoji("🧞‍♀️", "Peoples", ['woman_genie']),
new Emoji("🧟", "Peoples", ['zombie']),
new Emoji("🧟‍♂️", "Peoples", ['man_zombie']),
new Emoji("🧟‍♀️", "Peoples", ['woman_zombie']),
new Emoji("🧌", "Peoples", ['troll']),
new Emoji("💆", "Peoples", ['massage', 'person_getting_massage']),
new Emoji("💆‍♂️", "Peoples", ['man_getting_massage']),
new Emoji("💆‍♀️", "Peoples", ['woman_getting_massage']),
new Emoji("💇", "Peoples", ['haircut', 'person_getting_haircut']),
new Emoji("💇‍♂️", "Peoples", ['man_getting_haircut']),
new Emoji("💇‍♀️", "Peoples", ['woman_getting_haircut']),
new Emoji("🚶", "Peoples", ['person_walking', 'walking']),
new Emoji("🚶‍♂️", "Peoples", ['man_walking']),
new Emoji("🚶‍♀️", "Peoples", ['woman_walking']),
new Emoji("🧍", "Peoples", ['person_standing', 'standing']),
new Emoji("🧍‍♂️", "Peoples", ['man_standing']),
new Emoji("🧍‍♀️", "Peoples", ['woman_standing']),
new Emoji("🧎", "Peoples", ['kneeling', 'person_kneeling']),
new Emoji("🧎‍♂️", "Peoples", ['man_kneeling']),
new Emoji("🧎‍♀️", "Peoples", ['woman_kneeling']),
new Emoji("🧑‍🦯", "Peoples", ['person_with_probing_cane', 'person_with_white_cane']),
new Emoji("👨‍🦯", "Peoples", ['man_with_probing_cane', 'man_with_white_cane']),
new Emoji("👩‍🦯", "Peoples", ['woman_with_probing_cane', 'woman_with_white_cane']),
new Emoji("🧑‍🦼", "Peoples", ['person_in_motorized_wheelchair']),
new Emoji("👨‍🦼", "Peoples", ['man_in_motorized_wheelchair']),
new Emoji("👩‍🦼", "Peoples", ['woman_in_motorized_wheelchair']),
new Emoji("🧑‍🦽", "Peoples", ['person_in_manual_wheelchair']),
new Emoji("👨‍🦽", "Peoples", ['man_in_manual_wheelchair']),
new Emoji("👩‍🦽", "Peoples", ['woman_in_manual_wheelchair']),
new Emoji("🏃", "Peoples", ['person_running', 'running']),
new Emoji("🏃‍♂️", "Peoples", ['man_running']),
new Emoji("🏃‍♀️", "Peoples", ['woman_running']),
new Emoji("💃", "Peoples", ['dancer', 'woman_dancing']),
new Emoji("🕺", "Peoples", ['man_dancing']),
new Emoji("🕴️", "Peoples", ['levitate', 'levitating', 'person_in_suit_levitating']),
new Emoji("👯", "Peoples", ['dancers', 'people_with_bunny_ears_partying']),
new Emoji("👯‍♂️", "Peoples", ['men_with_bunny_ears_partying']),
new Emoji("👯‍♀️", "Peoples", ['women_with_bunny_ears_partying']),
new Emoji("🧖", "Peoples", ['person_in_steamy_room']),
new Emoji("🧖‍♂️", "Peoples", ['man_in_steamy_room']),
new Emoji("🧖‍♀️", "Peoples", ['woman_in_steamy_room']),
new Emoji("🧗", "Peoples", ['climbing', 'person_climbing']),
new Emoji("🧗‍♂️", "Peoples", ['man_climbing']),
new Emoji("🧗‍♀️", "Peoples", ['woman_climbing']),
new Emoji("🤺", "Peoples", ['fencer', 'fencing', 'person_fencing']),
new Emoji("🏇", "Peoples", ['horse_racing']),
new Emoji("⛷️", "Peoples", ['person_skiing', 'skier', 'skiing']),
new Emoji("🏂️", "Peoples", ['person_snowboarding', 'snowboarder', 'snowboarding']),
new Emoji("🏌️", "Peoples", ['golfer', 'golfing', 'person_golfing']),
new Emoji("🏌️‍♂️", "Peoples", ['man_golfing']),
new Emoji("🏌️‍♀️", "Peoples", ['woman_golfing']),
new Emoji("🏄️", "Peoples", ['person_surfing', 'surfer', 'surfing']),
new Emoji("🏄‍♂️", "Peoples", ['man_surfing']),
new Emoji("🏄‍♀️", "Peoples", ['woman_surfing']),
new Emoji("🚣", "Peoples", ['person_rowing_boat', 'rowboat']),
new Emoji("🚣‍♂️", "Peoples", ['man_rowing_boat']),
new Emoji("🚣‍♀️", "Peoples", ['woman_rowing_boat']),
new Emoji("🏊️", "Peoples", ['person_swimming', 'swimmer', 'swimming']),
new Emoji("🏊‍♂️", "Peoples", ['man_swimming']),
new Emoji("🏊‍♀️", "Peoples", ['woman_swimming']),
new Emoji("⛹️", "Peoples", ['person_bouncing_ball']),
new Emoji("⛹️‍♂️", "Peoples", ['man_bouncing_ball']),
new Emoji("⛹️‍♀️", "Peoples", ['woman_bouncing_ball']),
new Emoji("🏋️", "Peoples", ['person_lifting_weights', 'weight_lifter', 'weight_lifting']),
new Emoji("🏋️‍♂️", "Peoples", ['man_lifting_weights']),
new Emoji("🏋️‍♀️", "Peoples", ['woman_lifting_weights']),
new Emoji("🚴", "Peoples", ['bicyclist', 'biking', 'person_biking']),
new Emoji("🚴‍♂️", "Peoples", ['man_biking']),
new Emoji("🚴‍♀️", "Peoples", ['woman_biking']),
new Emoji("🚵", "Peoples", ['mountain_bicyclist', 'mountain_biking', 'person_mountain_biking']),
new Emoji("🚵‍♂️", "Peoples", ['man_mountain_biking']),
new Emoji("🚵‍♀️", "Peoples", ['woman_mountain_biking']),
new Emoji("🤸", "Peoples", ['cartwheeling', 'person_cartwheel']),
new Emoji("🤸‍♂️", "Peoples", ['man_cartwheeling']),
new Emoji("🤸‍♀️", "Peoples", ['woman_cartwheeling']),
new Emoji("🤼", "Peoples", ['people_wrestling', 'wrestlers', 'wrestling']),
new Emoji("🤼‍♂️", "Peoples", ['men_wrestling']),
new Emoji("🤼‍♀️", "Peoples", ['women_wrestling']),
new Emoji("🤽", "Peoples", ['person_playing_water_polo', 'water_polo']),
new Emoji("🤽‍♂️", "Peoples", ['man_playing_water_polo']),
new Emoji("🤽‍♀️", "Peoples", ['woman_playing_water_polo']),
new Emoji("🤾", "Peoples", ['handball', 'person_playing_handball']),
new Emoji("🤾‍♂️", "Peoples", ['man_playing_handball']),
new Emoji("🤾‍♀️", "Peoples", ['woman_playing_handball']),
new Emoji("🤹", "Peoples", ['juggler', 'juggling', 'person_juggling']),
new Emoji("🤹‍♂️", "Peoples", ['man_juggling']),
new Emoji("🤹‍♀️", "Peoples", ['woman_juggling']),
new Emoji("🧘", "Peoples", ['person_in_lotus_position']),
new Emoji("🧘‍♂️", "Peoples", ['man_in_lotus_position']),
new Emoji("🧘‍♀️", "Peoples", ['woman_in_lotus_position']),
new Emoji("🛀", "Peoples", ['bath', 'person_taking_bath']),
new Emoji("🛌", "Peoples", ['person_in_bed', 'sleeping_accommodation']),
new Emoji("🧑‍🤝‍🧑", "Peoples", ['people_holding_hands']),
new Emoji("👭", "Peoples", ['two_women_holding_hands']),
new Emoji("👫", "Peoples", ['couple']),
new Emoji("👬", "Peoples", ['two_men_holding_hands']),
new Emoji("💏", "Peoples", ['couple_kiss', 'couplekiss']),
new Emoji("👩‍❤️‍💋‍👨", "Peoples", ['kiss_mw', 'kiss_wm']),
new Emoji("👨‍❤️‍💋‍👨", "Peoples", ['kiss_mm']),
new Emoji("👩‍❤️‍💋‍👩", "Peoples", ['kiss_ww']),
new Emoji("💑", "Peoples", ['couple_with_heart']),
new Emoji("👩‍❤️‍👨", "Peoples", ['couple_with_heart_mw', 'couple_with_heart_wm']),
new Emoji("👨‍❤️‍👨", "Peoples", ['couple_with_heart_mm']),
new Emoji("👩‍❤️‍👩", "Peoples", ['couple_with_heart_ww']),
new Emoji("👪️", "Peoples", ['family']),
new Emoji("👨‍👩‍👦", "Peoples", ['family_mwb']),
new Emoji("👨‍👩‍👧", "Peoples", ['family_mwg']),
new Emoji("👨‍👩‍👧‍👦", "Peoples", ['family_mwgb']),
new Emoji("👨‍👩‍👦‍👦", "Peoples", ['family_mwbb']),
new Emoji("👨‍👩‍👧‍👧", "Peoples", ['family_mwgg']),
new Emoji("👨‍👨‍👦", "Peoples", ['family_mmb']),
new Emoji("👨‍👨‍👧", "Peoples", ['family_mmg']),
new Emoji("👨‍👨‍👧‍👦", "Peoples", ['family_mmgb']),
new Emoji("👨‍👨‍👦‍👦", "Peoples", ['family_mmbb']),
new Emoji("👨‍👨‍👧‍👧", "Peoples", ['family_mmgg']),
new Emoji("👩‍👩‍👦", "Peoples", ['family_wwb']),
new Emoji("👩‍👩‍👧", "Peoples", ['family_wwg']),
new Emoji("👩‍👩‍👧‍👦", "Peoples", ['family_wwgb']),
new Emoji("👩‍👩‍👦‍👦", "Peoples", ['family_wwbb']),
new Emoji("👩‍👩‍👧‍👧", "Peoples", ['family_wwgg']),
new Emoji("👨‍👦", "Peoples", ['family_mb']),
new Emoji("👨‍👦‍👦", "Peoples", ['family_mbb']),
new Emoji("👨‍👧", "Peoples", ['family_mg']),
new Emoji("👨‍👧‍👦", "Peoples", ['family_mgb']),
new Emoji("👨‍👧‍👧", "Peoples", ['family_mgg']),
new Emoji("👩‍👦", "Peoples", ['family_wb']),
new Emoji("👩‍👦‍👦", "Peoples", ['family_wbb']),
new Emoji("👩‍👧", "Peoples", ['family_wg']),
new Emoji("👩‍👧‍👦", "Peoples", ['family_wgb']),
new Emoji("👩‍👧‍👧", "Peoples", ['family_wgg']),
new Emoji("🗣️", "Peoples", ['speaking_head']),
new Emoji("👤", "Peoples", ['bust_in_silhouette']),
new Emoji("👥", "Peoples", ['busts_in_silhouette']),
new Emoji("🫂", "Peoples", ['people_hugging']),
new Emoji("👣", "Peoples", ['footprints']),
new Emoji("🏻", "Peoples", ['tone1', 'tone_light']),
new Emoji("🏼", "Peoples", ['tone2', 'tone_medium_light']),
new Emoji("🏽", "Peoples", ['tone3', 'tone_medium']),
new Emoji("🏾", "Peoples", ['tone4', 'tone_medium_dark']),
new Emoji("🏿", "Peoples", ['tone5', 'tone_dark']),
new Emoji("🦰", "Peoples", ['red_hair']),
new Emoji("🦱", "Peoples", ['curly_hair']),
new Emoji("🦳", "Peoples", ['white_hair']),
new Emoji("🦲", "Peoples", ['no_hair']),
new Emoji("🐵", "Nature", ['monkey_face']),
new Emoji("🐒", "Nature", ['monkey']),
new Emoji("🦍", "Nature", ['gorilla']),
new Emoji("🦧", "Nature", ['orangutan']),
new Emoji("🐶", "Nature", ['dog_face']),
new Emoji("🐕️", "Nature", ['dog']),
new Emoji("🦮", "Nature", ['guide_dog']),
new Emoji("🐕‍🦺", "Nature", ['service_dog']),
new Emoji("🐩", "Nature", ['poodle']),
new Emoji("🐺", "Nature", ['wolf', 'wolf_face']),
new Emoji("🦊", "Nature", ['fox', 'fox_face']),
new Emoji("🦝", "Nature", ['raccoon']),
new Emoji("🐱", "Nature", ['cat_face']),
new Emoji("🐈️", "Nature", ['cat']),
new Emoji("🐈‍⬛", "Nature", ['black_cat']),
new Emoji("🦁", "Nature", ['lion', 'lion_face']),
new Emoji("🐯", "Nature", ['tiger_face']),
new Emoji("🐅", "Nature", ['tiger']),
new Emoji("🐆", "Nature", ['leopard']),
new Emoji("🐴", "Nature", ['horse_face']),
new Emoji("🐎", "Nature", ['horse', 'racehorse']),
new Emoji("🦄", "Nature", ['unicorn', 'unicorn_face']),
new Emoji("🦓", "Nature", ['zebra']),
new Emoji("🦌", "Nature", ['deer']),
new Emoji("🦬", "Nature", ['bison']),
new Emoji("🐮", "Nature", ['cow_face']),
new Emoji("🐂", "Nature", ['ox']),
new Emoji("🐃", "Nature", ['water_buffalo']),
new Emoji("🐄", "Nature", ['cow']),
new Emoji("🐷", "Nature", ['pig_face']),
new Emoji("🐖", "Nature", ['pig']),
new Emoji("🐗", "Nature", ['boar']),
new Emoji("🐽", "Nature", ['pig_nose']),
new Emoji("🐏", "Nature", ['ram']),
new Emoji("🐑", "Nature", ['ewe', 'sheep']),
new Emoji("🐐", "Nature", ['goat']),
new Emoji("🐪", "Nature", ['dromedary_camel']),
new Emoji("🐫", "Nature", ['camel']),
new Emoji("🦙", "Nature", ['llama']),
new Emoji("🦒", "Nature", ['giraffe']),
new Emoji("🐘", "Nature", ['elephant']),
new Emoji("🦣", "Nature", ['mammoth']),
new Emoji("🦏", "Nature", ['rhino', 'rhinoceros']),
new Emoji("🦛", "Nature", ['hippo']),
new Emoji("🐭", "Nature", ['mouse_face']),
new Emoji("🐁", "Nature", ['mouse']),
new Emoji("🐀", "Nature", ['rat']),
new Emoji("🐹", "Nature", ['hamster', 'hamster_face']),
new Emoji("🐰", "Nature", ['rabbit_face']),
new Emoji("🐇", "Nature", ['rabbit']),
new Emoji("🐿️", "Nature", ['chipmunk']),
new Emoji("🦫", "Nature", ['beaver']),
new Emoji("🦔", "Nature", ['hedgehog']),
new Emoji("🦇", "Nature", ['bat']),
new Emoji("🐻", "Nature", ['bear', 'bear_face']),
new Emoji("🐻‍❄️", "Nature", ['polar_bear', 'polar_bear_face']),
new Emoji("🐨", "Nature", ['koala', 'koala_face']),
new Emoji("🐼", "Nature", ['panda', 'panda_face']),
new Emoji("🦥", "Nature", ['sloth']),
new Emoji("🦦", "Nature", ['otter']),
new Emoji("🦨", "Nature", ['skunk']),
new Emoji("🦘", "Nature", ['kangaroo']),
new Emoji("🦡", "Nature", ['badger']),
new Emoji("🐾", "Nature", ['paw_prints']),
new Emoji("🦃", "Nature", ['turkey']),
new Emoji("🐔", "Nature", ['chicken', 'chicken_face']),
new Emoji("🐓", "Nature", ['rooster']),
new Emoji("🐣", "Nature", ['hatching_chick']),
new Emoji("🐤", "Nature", ['baby_chick']),
new Emoji("🐥", "Nature", ['hatched_chick']),
new Emoji("🐦️", "Nature", ['bird', 'bird_face']),
new Emoji("🐧", "Nature", ['penguin', 'penguin_face']),
new Emoji("🕊️", "Nature", ['dove']),
new Emoji("🦅", "Nature", ['eagle']),
new Emoji("🦆", "Nature", ['duck']),
new Emoji("🦢", "Nature", ['swan']),
new Emoji("🦉", "Nature", ['owl']),
new Emoji("🦤", "Nature", ['dodo']),
new Emoji("🪶", "Nature", ['feather']),
new Emoji("🦩", "Nature", ['flamingo']),
new Emoji("🦚", "Nature", ['peacock']),
new Emoji("🦜", "Nature", ['parrot']),
new Emoji("🐸", "Nature", ['frog', 'frog_face']),
new Emoji("🐊", "Nature", ['crocodile']),
new Emoji("🐢", "Nature", ['turtle']),
new Emoji("🦎", "Nature", ['lizard']),
new Emoji("🐍", "Nature", ['snake']),
new Emoji("🐲", "Nature", ['dragon_face']),
new Emoji("🐉", "Nature", ['dragon']),
new Emoji("🦕", "Nature", ['sauropod']),
new Emoji("🦖", "Nature", ['t-rex', 'trex']),
new Emoji("🐳", "Nature", ['spouting_whale']),
new Emoji("🐋", "Nature", ['whale']),
new Emoji("🐬", "Nature", ['dolphin']),
new Emoji("🦭", "Nature", ['seal']),
new Emoji("🐟️", "Nature", ['fish']),
new Emoji("🐠", "Nature", ['tropical_fish']),
new Emoji("🐡", "Nature", ['blowfish']),
new Emoji("🦈", "Nature", ['shark']),
new Emoji("🐙", "Nature", ['octopus']),
new Emoji("🐚", "Nature", ['shell']),
new Emoji("🪸", "Nature", ['coral']),
new Emoji("🐌", "Nature", ['snail']),
new Emoji("🦋", "Nature", ['butterfly']),
new Emoji("🐛", "Nature", ['bug']),
new Emoji("🐜", "Nature", ['ant']),
new Emoji("🐝", "Nature", ['bee']),
new Emoji("🪲", "Nature", ['beetle']),
new Emoji("🐞", "Nature", ['lady_beetle']),
new Emoji("🦗", "Nature", ['cricket']),
new Emoji("🪳", "Nature", ['cockroach']),
new Emoji("🕷️", "Nature", ['spider']),
new Emoji("🕸️", "Nature", ['spider_web']),
new Emoji("🦂", "Nature", ['scorpion']),
new Emoji("🦟", "Nature", ['mosquito']),
new Emoji("🪰", "Nature", ['fly']),
new Emoji("🪱", "Nature", ['worm']),
new Emoji("🦠", "Nature", ['microbe']),
new Emoji("💐", "Nature", ['bouquet']),
new Emoji("🌸", "Nature", ['cherry_blossom']),
new Emoji("💮", "Nature", ['white_flower']),
new Emoji("🪷", "Nature", ['lotus']),
new Emoji("🏵️", "Nature", ['rosette']),
new Emoji("🌹", "Nature", ['rose']),
new Emoji("🥀", "Nature", ['wilted_flower']),
new Emoji("🌺", "Nature", ['hibiscus']),
new Emoji("🌻", "Nature", ['sunflower']),
new Emoji("🌼", "Nature", ['blossom']),
new Emoji("🌷", "Nature", ['tulip']),
new Emoji("🌱", "Nature", ['seedling']),
new Emoji("🪴", "Nature", ['potted_plant']),
new Emoji("🌲", "Nature", ['evergreen_tree']),
new Emoji("🌳", "Nature", ['deciduous_tree']),
new Emoji("🌴", "Nature", ['palm_tree']),
new Emoji("🌵", "Nature", ['cactus']),
new Emoji("🌾", "Nature", ['ear_of_rice', 'sheaf_of_rice']),
new Emoji("🌿", "Nature", ['herb']),
new Emoji("☘️", "Nature", ['shamrock']),
new Emoji("🍀", "Nature", ['four_leaf_clover']),
new Emoji("🍁", "Nature", ['maple_leaf']),
new Emoji("🍂", "Nature", ['fallen_leaf']),
new Emoji("🍃", "Nature", ['leaves']),
new Emoji("🪹", "Nature", ['empty_nest', 'nest']),
new Emoji("🪺", "Nature", ['nest_with_eggs']),
new Emoji("🍇", "Foods", ['grapes']),
new Emoji("🍈", "Foods", ['melon']),
new Emoji("🍉", "Foods", ['watermelon']),
new Emoji("🍊", "Foods", ['orange', 'tangerine']),
new Emoji("🍋", "Foods", ['lemon']),
new Emoji("🍌", "Foods", ['banana']),
new Emoji("🍍", "Foods", ['pineapple']),
new Emoji("🥭", "Foods", ['mango']),
new Emoji("🍎", "Foods", ['apple', 'red_apple']),
new Emoji("🍏", "Foods", ['green_apple']),
new Emoji("🍐", "Foods", ['pear']),
new Emoji("🍑", "Foods", ['peach']),
new Emoji("🍒", "Foods", ['cherries']),
new Emoji("🍓", "Foods", ['strawberry']),
new Emoji("🫐", "Foods", ['blueberries']),
new Emoji("🥝", "Foods", ['kiwi']),
new Emoji("🍅", "Foods", ['tomato']),
new Emoji("🫒", "Foods", ['olive']),
new Emoji("🥥", "Foods", ['coconut']),
new Emoji("🥑", "Foods", ['avocado']),
new Emoji("🍆", "Foods", ['eggplant']),
new Emoji("🥔", "Foods", ['potato']),
new Emoji("🥕", "Foods", ['carrot']),
new Emoji("🌽", "Foods", ['corn', 'ear_of_corn']),
new Emoji("🌶️", "Foods", ['hot_pepper']),
new Emoji("🫑", "Foods", ['bell_pepper']),
new Emoji("🥒", "Foods", ['cucumber']),
new Emoji("🥬", "Foods", ['leafy_green']),
new Emoji("🥦", "Foods", ['broccoli']),
new Emoji("🧄", "Foods", ['garlic']),
new Emoji("🧅", "Foods", ['onion']),
new Emoji("🍄", "Foods", ['mushroom']),
new Emoji("🥜", "Foods", ['peanuts']),
new Emoji("🫘", "Foods", ['beans']),
new Emoji("🌰", "Foods", ['chestnut']),
new Emoji("🍞", "Foods", ['bread']),
new Emoji("🥐", "Foods", ['croissant']),
new Emoji("🥖", "Foods", ['baguette_bread']),
new Emoji("🫓", "Foods", ['flatbread']),
new Emoji("🥨", "Foods", ['pretzel']),
new Emoji("🥯", "Foods", ['bagel']),
new Emoji("🥞", "Foods", ['pancakes']),
new Emoji("🧇", "Foods", ['waffle']),
new Emoji("🧀", "Foods", ['cheese']),
new Emoji("🍖", "Foods", ['meat_on_bone']),
new Emoji("🍗", "Foods", ['poultry_leg']),
new Emoji("🥩", "Foods", ['cut_of_meat']),
new Emoji("🥓", "Foods", ['bacon']),
new Emoji("🍔", "Foods", ['hamburger']),
new Emoji("🍟", "Foods", ['french_fries', 'fries']),
new Emoji("🍕", "Foods", ['pizza']),
new Emoji("🌭", "Foods", ['hotdog']),
new Emoji("🥪", "Foods", ['sandwich']),
new Emoji("🌮", "Foods", ['taco']),
new Emoji("🌯", "Foods", ['burrito']),
new Emoji("🫔", "Foods", ['tamale']),
new Emoji("🥙", "Foods", ['stuffed_flatbread']),
new Emoji("🧆", "Foods", ['falafel']),
new Emoji("🥚", "Foods", ['egg']),
new Emoji("🍳", "Foods", ['cooking', 'fried_egg']),
new Emoji("🥘", "Foods", ['shallow_pan_of_food']),
new Emoji("🍲", "Foods", ['pot_of_food', 'stew']),
new Emoji("🫕", "Foods", ['fondue']),
new Emoji("🥣", "Foods", ['bowl_with_spoon']),
new Emoji("🥗", "Foods", ['green_salad', 'salad']),
new Emoji("🍿", "Foods", ['popcorn']),
new Emoji("🧈", "Foods", ['butter']),
new Emoji("🧂", "Foods", ['salt']),
new Emoji("🥫", "Foods", ['canned_food']),
new Emoji("🍱", "Foods", ['bento', 'bento_box']),
new Emoji("🍘", "Foods", ['rice_cracker']),
new Emoji("🍙", "Foods", ['rice_ball']),
new Emoji("🍚", "Foods", ['cooked_rice', 'rice']),
new Emoji("🍛", "Foods", ['curry', 'curry_rice']),
new Emoji("🍜", "Foods", ['ramen', 'steaming_bowl']),
new Emoji("🍝", "Foods", ['spaghetti']),
new Emoji("🍠", "Foods", ['sweet_potato']),
new Emoji("🍢", "Foods", ['oden']),
new Emoji("🍣", "Foods", ['sushi']),
new Emoji("🍤", "Foods", ['fried_shrimp']),
new Emoji("🍥", "Foods", ['fish_cake']),
new Emoji("🥮", "Foods", ['moon_cake']),
new Emoji("🍡", "Foods", ['dango']),
new Emoji("🥟", "Foods", ['dumpling']),
new Emoji("🥠", "Foods", ['fortune_cookie']),
new Emoji("🥡", "Foods", ['takeout_box']),
new Emoji("🦀", "Foods", ['crab']),
new Emoji("🦞", "Foods", ['lobster']),
new Emoji("🦐", "Foods", ['shrimp']),
new Emoji("🦑", "Foods", ['squid']),
new Emoji("🦪", "Foods", ['oyster']),
new Emoji("🍦", "Foods", ['icecream', 'soft_serve']),
new Emoji("🍧", "Foods", ['shaved_ice']),
new Emoji("🍨", "Foods", ['ice_cream']),
new Emoji("🍩", "Foods", ['doughnut']),
new Emoji("🍪", "Foods", ['cookie']),
new Emoji("🎂", "Foods", ['birthday', 'birthday_cake']),
new Emoji("🍰", "Foods", ['cake', 'shortcake']),
new Emoji("🧁", "Foods", ['cupcake']),
new Emoji("🥧", "Foods", ['pie']),
new Emoji("🍫", "Foods", ['chocolate_bar']),
new Emoji("🍬", "Foods", ['candy']),
new Emoji("🍭", "Foods", ['lollipop']),
new Emoji("🍮", "Foods", ['custard']),
new Emoji("🍯", "Foods", ['honey_pot']),
new Emoji("🍼", "Foods", ['baby_bottle']),
new Emoji("🥛", "Foods", ['glass_of_milk', 'milk']),
new Emoji("☕️", "Foods", ['coffee']),
new Emoji("🫖", "Foods", ['teapot']),
new Emoji("🍵", "Foods", ['tea']),
new Emoji("🍶", "Foods", ['sake']),
new Emoji("🍾", "Foods", ['champagne']),
new Emoji("🍷", "Foods", ['wine_glass']),
new Emoji("🍸️", "Foods", ['cocktail']),
new Emoji("🍹", "Foods", ['tropical_drink']),
new Emoji("🍺", "Foods", ['beer']),
new Emoji("🍻", "Foods", ['beers']),
new Emoji("🥂", "Foods", ['clinking_glasses']),
new Emoji("🥃", "Foods", ['tumbler_glass', 'whisky']),
new Emoji("🫗", "Foods", ['pour', 'pouring_liquid']),
new Emoji("🥤", "Foods", ['cup_with_straw']),
new Emoji("🧋", "Foods", ['boba_drink', 'bubble_tea']),
new Emoji("🧃", "Foods", ['beverage_box', 'juice_box']),
new Emoji("🧉", "Foods", ['mate']),
new Emoji("🧊", "Foods", ['ice', 'ice_cube']),
new Emoji("🥢", "Foods", ['chopsticks']),
new Emoji("🍽️", "Foods", ['fork_knife_plate']),
new Emoji("🍴", "Foods", ['fork_and_knife']),
new Emoji("🥄", "Foods", ['spoon']),
new Emoji("🔪", "Foods", ['knife']),
new Emoji("🫙", "Foods", ['jar']),
new Emoji("🏺", "Foods", ['amphora']),
new Emoji("🌍️", "Places", ['earth_africa', 'earth_europe']),
new Emoji("🌎️", "Places", ['earth_americas']),
new Emoji("🌏️", "Places", ['earth_asia']),
new Emoji("🌐", "Places", ['globe_with_meridians']),
new Emoji("🗺️", "Places", ['world_map']),
new Emoji("🗾", "Places", ['japan_map']),
new Emoji("🧭", "Places", ['compass']),
new Emoji("🏔️", "Places", ['mountain_snow']),
new Emoji("⛰️", "Places", ['mountain']),
new Emoji("🌋", "Places", ['volcano']),
new Emoji("🗻", "Places", ['mount_fuji']),
new Emoji("🏕️", "Places", ['camping']),
new Emoji("🏖️", "Places", ['beach', 'beach_with_umbrella']),
new Emoji("🏜️", "Places", ['desert']),
new Emoji("🏝️", "Places", ['desert_island', 'island']),
new Emoji("🏞️", "Places", ['national_park']),
new Emoji("🏟️", "Places", ['stadium']),
new Emoji("🏛️", "Places", ['classical_building']),
new Emoji("🏗️", "Places", ['building_construction', 'construction_site']),
new Emoji("🧱", "Places", ['bricks']),
new Emoji("🪨", "Places", ['rock']),
new Emoji("🪵", "Places", ['wood']),
new Emoji("🛖", "Places", ['hut']),
new Emoji("🏘️", "Places", ['homes', 'houses']),
new Emoji("🏚️", "Places", ['derelict_house', 'house_abandoned']),
new Emoji("🏠️", "Places", ['house']),
new Emoji("🏡", "Places", ['house_with_garden']),
new Emoji("🏢", "Places", ['office']),
new Emoji("🏣", "Places", ['post_office']),
new Emoji("🏤", "Places", ['european_post_office']),
new Emoji("🏥", "Places", ['hospital']),
new Emoji("🏦", "Places", ['bank']),
new Emoji("🏨", "Places", ['hotel']),
new Emoji("🏩", "Places", ['love_hotel']),
new Emoji("🏪", "Places", ['convenience_store']),
new Emoji("🏫", "Places", ['school']),
new Emoji("🏬", "Places", ['department_store']),
new Emoji("🏭️", "Places", ['factory']),
new Emoji("🏯", "Places", ['japanese_castle']),
new Emoji("🏰", "Places", ['castle', 'european_castle']),
new Emoji("💒", "Places", ['wedding']),
new Emoji("🗼", "Places", ['tokyo_tower']),
new Emoji("🗽", "Places", ['statue_of_liberty']),
new Emoji("⛪️", "Places", ['church']),
new Emoji("🕌", "Places", ['mosque']),
new Emoji("🛕", "Places", ['hindu_temple']),
new Emoji("🕍", "Places", ['synagogue']),
new Emoji("⛩️", "Places", ['shinto_shrine']),
new Emoji("🕋", "Places", ['kaaba']),
new Emoji("⛲️", "Places", ['fountain']),
new Emoji("⛺️", "Places", ['tent']),
new Emoji("🌁", "Places", ['foggy']),
new Emoji("🌃", "Places", ['night_with_stars']),
new Emoji("🏙️", "Places", ['cityscape']),
new Emoji("🌄", "Places", ['sunrise_over_mountains']),
new Emoji("🌅", "Places", ['sunrise']),
new Emoji("🌆", "Places", ['city_dusk']),
new Emoji("🌇", "Places", ['city_sunrise', 'city_sunset']),
new Emoji("🌉", "Places", ['bridge_at_night']),
new Emoji("♨️", "Places", ['hotsprings']),
new Emoji("🎠", "Places", ['carousel_horse']),
new Emoji("🛝", "Places", ['playground_slide', 'slide']),
new Emoji("🎡", "Places", ['ferris_wheel']),
new Emoji("🎢", "Places", ['roller_coaster']),
new Emoji("💈", "Places", ['barber', 'barber_pole']),
new Emoji("🎪", "Places", ['circus_tent']),
new Emoji("🚂", "Places", ['steam_locomotive']),
new Emoji("🚃", "Places", ['railway_car']),
new Emoji("🚄", "Places", ['bullettrain_side']),
new Emoji("🚅", "Places", ['bullettrain_front']),
new Emoji("🚆", "Places", ['train']),
new Emoji("🚇️", "Places", ['metro']),
new Emoji("🚈", "Places", ['light_rail']),
new Emoji("🚉", "Places", ['station']),
new Emoji("🚊", "Places", ['tram']),
new Emoji("🚝", "Places", ['monorail']),
new Emoji("🚞", "Places", ['mountain_railway']),
new Emoji("🚋", "Places", ['tram_car']),
new Emoji("🚌", "Places", ['bus']),
new Emoji("🚍️", "Places", ['oncoming_bus']),
new Emoji("🚎", "Places", ['trolleybus']),
new Emoji("🚐", "Places", ['minibus']),
new Emoji("🚑️", "Places", ['ambulance']),
new Emoji("🚒", "Places", ['fire_engine']),
new Emoji("🚓", "Places", ['police_car']),
new Emoji("🚔️", "Places", ['oncoming_police_car']),
new Emoji("🚕", "Places", ['taxi']),
new Emoji("🚖", "Places", ['oncoming_taxi']),
new Emoji("🚗", "Places", ['car', 'red_car']),
new Emoji("🚘️", "Places", ['oncoming_automobile']),
new Emoji("🚙", "Places", ['blue_car', 'suv']),
new Emoji("🛻", "Places", ['pickup_truck']),
new Emoji("🚚", "Places", ['delivery_truck', 'truck']),
new Emoji("🚛", "Places", ['articulated_lorry']),
new Emoji("🚜", "Places", ['tractor']),
new Emoji("🏎️", "Places", ['racing_car']),
new Emoji("🏍️", "Places", ['motorcycle']),
new Emoji("🛵", "Places", ['motor_scooter']),
new Emoji("🦽", "Places", ['manual_wheelchair']),
new Emoji("🦼", "Places", ['motorized_wheelchair']),
new Emoji("🛺", "Places", ['auto_rickshaw']),
new Emoji("🚲️", "Places", ['bicycle', 'bike']),
new Emoji("🛴", "Places", ['scooter']),
new Emoji("🛹", "Places", ['skateboard']),
new Emoji("🛼", "Places", ['roller_skate']),
new Emoji("🚏", "Places", ['busstop']),
new Emoji("🛣️", "Places", ['motorway']),
new Emoji("🛤️", "Places", ['railway_track']),
new Emoji("🛢️", "Places", ['oil_drum']),
new Emoji("⛽️", "Places", ['fuelpump']),
new Emoji("🛞", "Places", ['wheel']),
new Emoji("🚨", "Places", ['rotating_light']),
new Emoji("🚥", "Places", ['traffic_light']),
new Emoji("🚦", "Places", ['vertical_traffic_light']),
new Emoji("🛑", "Places", ['octagonal_sign', 'stop_sign']),
new Emoji("🚧", "Places", ['construction']),
new Emoji("⚓️", "Places", ['anchor']),
new Emoji("🛟", "Places", ['lifebuoy', 'ring_buoy']),
new Emoji("⛵️", "Places", ['sailboat']),
new Emoji("🛶", "Places", ['canoe']),
new Emoji("🚤", "Places", ['speedboat']),
new Emoji("🛳️", "Places", ['cruise_ship', 'passenger_ship']),
new Emoji("⛴️", "Places", ['ferry']),
new Emoji("🛥️", "Places", ['motorboat']),
new Emoji("🚢", "Places", ['ship']),
new Emoji("✈️", "Places", ['airplane']),
new Emoji("🛩️", "Places", ['small_airplane']),
new Emoji("🛫", "Places", ['airplane_departure']),
new Emoji("🛬", "Places", ['airplane_arriving']),
new Emoji("🪂", "Places", ['parachute']),
new Emoji("💺", "Places", ['seat']),
new Emoji("🚁", "Places", ['helicopter']),
new Emoji("🚟", "Places", ['suspension_railway']),
new Emoji("🚠", "Places", ['mountain_cableway']),
new Emoji("🚡", "Places", ['aerial_tramway']),
new Emoji("🛰️", "Places", ['satellite']),
new Emoji("🚀", "Places", ['rocket']),
new Emoji("🛸", "Places", ['flying_saucer']),
new Emoji("🛎️", "Places", ['bellhop']),
new Emoji("🧳", "Places", ['luggage']),
new Emoji("⌛️", "Places", ['hourglass']),
new Emoji("⏳️", "Places", ['hourglass_flowing_sand']),
new Emoji("⌚️", "Places", ['watch']),
new Emoji("⏰", "Places", ['alarm_clock']),
new Emoji("⏱️", "Places", ['stopwatch']),
new Emoji("⏲️", "Places", ['timer_clock']),
new Emoji("🕰️", "Places", ['clock']),
new Emoji("🕛️", "Places", ['clock12']),
new Emoji("🕧️", "Places", ['clock1230']),
new Emoji("🕐️", "Places", ['clock1']),
new Emoji("🕜️", "Places", ['clock130']),
new Emoji("🕑️", "Places", ['clock2']),
new Emoji("🕝️", "Places", ['clock230']),
new Emoji("🕒️", "Places", ['clock3']),
new Emoji("🕞️", "Places", ['clock330']),
new Emoji("🕓️", "Places", ['clock4']),
new Emoji("🕟️", "Places", ['clock430']),
new Emoji("🕔️", "Places", ['clock5']),
new Emoji("🕠️", "Places", ['clock530']),
new Emoji("🕕️", "Places", ['clock6']),
new Emoji("🕡️", "Places", ['clock630']),
new Emoji("🕖️", "Places", ['clock7']),
new Emoji("🕢️", "Places", ['clock730']),
new Emoji("🕗️", "Places", ['clock8']),
new Emoji("🕣️", "Places", ['clock830']),
new Emoji("🕘️", "Places", ['clock9']),
new Emoji("🕤️", "Places", ['clock930']),
new Emoji("🕙️", "Places", ['clock10']),
new Emoji("🕥️", "Places", ['clock1030']),
new Emoji("🕚️", "Places", ['clock11']),
new Emoji("🕦️", "Places", ['clock1130']),
new Emoji("🌑", "Places", ['new_moon']),
new Emoji("🌒", "Places", ['waxing_crescent_moon']),
new Emoji("🌓", "Places", ['first_quarter_moon']),
new Emoji("🌔", "Places", ['waxing_gibbous_moon']),
new Emoji("🌕️", "Places", ['full_moon']),
new Emoji("🌖", "Places", ['waning_gibbous_moon']),
new Emoji("🌗", "Places", ['last_quarter_moon']),
new Emoji("🌘", "Places", ['waning_crescent_moon']),
new Emoji("🌙", "Places", ['crescent_moon']),
new Emoji("🌚", "Places", ['new_moon_with_face']),
new Emoji("🌛", "Places", ['first_quarter_moon_with_face']),
new Emoji("🌜️", "Places", ['last_quarter_moon_with_face']),
new Emoji("🌡️", "Places", ['thermometer']),
new Emoji("☀️", "Places", ['sun']),
new Emoji("🌝", "Places", ['full_moon_with_face']),
new Emoji("🌞", "Places", ['sun_with_face']),
new Emoji("🪐", "Places", ['ringed_planet', 'saturn']),
new Emoji("⭐️", "Places", ['star']),
new Emoji("🌟", "Places", ['glowing_star', 'star2']),
new Emoji("🌠", "Places", ['shooting_star', 'stars']),
new Emoji("🌌", "Places", ['milky_way']),
new Emoji("☁️", "Places", ['cloud']),
new Emoji("⛅️", "Places", ['partly_sunny', 'sun_behind_cloud']),
new Emoji("⛈️", "Places", ['stormy', 'thunder_cloud_and_rain']),
new Emoji("🌤️", "Places", ['sun_behind_small_cloud', 'sunny']),
new Emoji("🌥️", "Places", ['cloudy', 'sun_behind_large_cloud']),
new Emoji("🌦️", "Places", ['sun_and_rain', 'sun_behind_rain_cloud']),
new Emoji("🌧️", "Places", ['cloud_with_rain', 'rainy']),
new Emoji("🌨️", "Places", ['cloud_with_snow', 'snowy']),
new Emoji("🌩️", "Places", ['cloud_with_lightning', 'lightning']),
new Emoji("🌪️", "Places", ['tornado']),
new Emoji("🌫️", "Places", ['fog']),
new Emoji("🌬️", "Places", ['wind_blowing_face']),
new Emoji("🌀", "Places", ['cyclone']),
new Emoji("🌈", "Places", ['rainbow']),
new Emoji("🌂", "Places", ['closed_umbrella']),
new Emoji("☂️", "Places", ['umbrella']),
new Emoji("☔️", "Places", ['umbrella_with_rain']),
new Emoji("⛱️", "Places", ['beach_umbrella', 'umbrella_on_ground']),
new Emoji("⚡️", "Places", ['high_voltage', 'zap']),
new Emoji("❄️", "Places", ['snowflake']),
new Emoji("☃️", "Places", ['snowman2']),
new Emoji("⛄️", "Places", ['snowman']),
new Emoji("☄️", "Places", ['comet']),
new Emoji("🔥", "Places", ['fire']),
new Emoji("💧", "Places", ['droplet']),
new Emoji("🌊", "Places", ['ocean', 'water_wave']),
new Emoji("🎃", "Activity", ['jack_o_lantern']),
new Emoji("🎄", "Activity", ['christmas_tree']),
new Emoji("🎆", "Activity", ['fireworks']),
new Emoji("🎇", "Activity", ['sparkler']),
new Emoji("🧨", "Activity", ['firecracker']),
new Emoji("✨", "Activity", ['sparkles']),
new Emoji("🎈", "Activity", ['balloon']),
new Emoji("🎉", "Activity", ['party', 'party_popper', 'tada']),
new Emoji("🎊", "Activity", ['confetti_ball']),
new Emoji("🎋", "Activity", ['tanabata_tree']),
new Emoji("🎍", "Activity", ['bamboo']),
new Emoji("🎎", "Activity", ['dolls']),
new Emoji("🎏", "Activity", ['carp_streamer', 'flags']),
new Emoji("🎐", "Activity", ['wind_chime']),
new Emoji("🎑", "Activity", ['moon_ceremony', 'rice_scene']),
new Emoji("🧧", "Activity", ['red_envelope']),
new Emoji("🎀", "Activity", ['ribbon']),
new Emoji("🎁", "Activity", ['gift']),
new Emoji("🎗️", "Activity", ['reminder_ribbon']),
new Emoji("🎟️", "Activity", ['admission_tickets', 'tickets']),
new Emoji("🎫", "Activity", ['ticket']),
new Emoji("🎖️", "Activity", ['military_medal']),
new Emoji("🏆️", "Activity", ['trophy']),
new Emoji("🏅", "Activity", ['sports_medal']),
new Emoji("🥇", "Activity", ['1st', 'first_place_medal']),
new Emoji("🥈", "Activity", ['2nd', 'second_place_medal']),
new Emoji("🥉", "Activity", ['3rd', 'third_place_medal']),
new Emoji("⚽️", "Activity", ['soccer']),
new Emoji("⚾️", "Activity", ['baseball']),
new Emoji("🥎", "Activity", ['softball']),
new Emoji("🏀", "Activity", ['basketball']),
new Emoji("🏐", "Activity", ['volleyball']),
new Emoji("🏈", "Activity", ['football']),
new Emoji("🏉", "Activity", ['rugby_football']),
new Emoji("🎾", "Activity", ['tennis']),
new Emoji("🥏", "Activity", ['flying_disc']),
new Emoji("🎳", "Activity", ['bowling']),
new Emoji("🏏", "Activity", ['cricket_game']),
new Emoji("🏑", "Activity", ['field_hockey']),
new Emoji("🏒", "Activity", ['hockey']),
new Emoji("🥍", "Activity", ['lacrosse']),
new Emoji("🏓", "Activity", ['ping_pong']),
new Emoji("🏸", "Activity", ['badminton']),
new Emoji("🥊", "Activity", ['boxing_glove']),
new Emoji("🥋", "Activity", ['martial_arts_uniform']),
new Emoji("🥅", "Activity", ['goal_net']),
new Emoji("⛳️", "Activity", ['golf']),
new Emoji("⛸️", "Activity", ['ice_skate']),
new Emoji("🎣", "Activity", ['fishing_pole', 'fishing_pole_and_fish']),
new Emoji("🤿", "Activity", ['diving_mask']),
new Emoji("🎽", "Activity", ['running_shirt', 'running_shirt_with_sash']),
new Emoji("🎿", "Activity", ['ski']),
new Emoji("🛷", "Activity", ['sled']),
new Emoji("🥌", "Activity", ['curling_stone']),
new Emoji("🎯", "Activity", ['bullseye', 'dart', 'direct_hit']),
new Emoji("🪀", "Activity", ['yo_yo']),
new Emoji("🪁", "Activity", ['kite']),
new Emoji("🎱", "Activity", ['8ball', 'billiards']),
new Emoji("🔮", "Activity", ['crystal_ball']),
new Emoji("🪄", "Activity", ['magic_wand']),
new Emoji("🧿", "Activity", ['nazar_amulet']),
new Emoji("🪬", "Activity", ['hamsa']),
new Emoji("🎮️", "Activity", ['controller', 'video_game']),
new Emoji("🕹️", "Activity", ['joystick']),
new Emoji("🎰", "Activity", ['slot_machine']),
new Emoji("🎲", "Activity", ['game_die']),
new Emoji("🧩", "Activity", ['jigsaw', 'puzzle_piece']),
new Emoji("🧸", "Activity", ['teddy_bear']),
new Emoji("🪅", "Activity", ['pinata']),
new Emoji("🪩", "Activity", ['disco', 'disco_ball', 'mirror_ball']),
new Emoji("🪆", "Activity", ['nesting_dolls']),
new Emoji("♠️", "Activity", ['spades']),
new Emoji("♥️", "Activity", ['hearts']),
new Emoji("♦️", "Activity", ['diamonds']),
new Emoji("♣️", "Activity", ['clubs']),
new Emoji("♟️", "Activity", ['chess_pawn']),
new Emoji("🃏", "Activity", ['black_joker']),
new Emoji("🀄️", "Activity", ['mahjong']),
new Emoji("🎴", "Activity", ['flower_playing_cards']),
new Emoji("🎭️", "Activity", ['performing_arts']),
new Emoji("🖼️", "Activity", ['frame_with_picture', 'framed_picture']),
new Emoji("🎨", "Activity", ['art', 'palette']),
new Emoji("🧵", "Activity", ['thread']),
new Emoji("🪡", "Activity", ['sewing_needle']),
new Emoji("🧶", "Activity", ['yarn']),
new Emoji("🪢", "Activity", ['knot']),
new Emoji("👓️", "Objects", ['eyeglasses', 'glasses']),
new Emoji("🕶️", "Objects", ['sunglasses']),
new Emoji("🥽", "Objects", ['goggles']),
new Emoji("🥼", "Objects", ['lab_coat']),
new Emoji("🦺", "Objects", ['safety_vest']),
new Emoji("👔", "Objects", ['necktie']),
new Emoji("👕", "Objects", ['shirt']),
new Emoji("👖", "Objects", ['jeans']),
new Emoji("🧣", "Objects", ['scarf']),
new Emoji("🧤", "Objects", ['gloves']),
new Emoji("🧥", "Objects", ['coat']),
new Emoji("🧦", "Objects", ['socks']),
new Emoji("👗", "Objects", ['dress']),
new Emoji("👘", "Objects", ['kimono']),
new Emoji("🥻", "Objects", ['sari']),
new Emoji("🩱", "Objects", ['one_piece_swimsuit']),
new Emoji("🩲", "Objects", ['briefs']),
new Emoji("🩳", "Objects", ['shorts']),
new Emoji("👙", "Objects", ['bikini']),
new Emoji("👚", "Objects", ['womans_clothes']),
new Emoji("👛", "Objects", ['purse']),
new Emoji("👜", "Objects", ['handbag']),
new Emoji("👝", "Objects", ['clutch_bag', 'pouch']),
new Emoji("🛍️", "Objects", ['shopping_bags']),
new Emoji("🎒", "Objects", ['backpack', 'school_satchel']),
new Emoji("🩴", "Objects", ['thong_sandal']),
new Emoji("👞", "Objects", ['mans_shoe']),
new Emoji("👟", "Objects", ['athletic_shoe', 'sneaker']),
new Emoji("🥾", "Objects", ['hiking_boot']),
new Emoji("🥿", "Objects", ['flat_shoe', 'womans_flat_shoe']),
new Emoji("👠", "Objects", ['high_heel']),
new Emoji("👡", "Objects", ['sandal']),
new Emoji("🩰", "Objects", ['ballet_shoes']),
new Emoji("👢", "Objects", ['boot']),
new Emoji("👑", "Objects", ['crown']),
new Emoji("👒", "Objects", ['womans_hat']),
new Emoji("🎩", "Objects", ['top_hat', 'tophat']),
new Emoji("🎓️", "Objects", ['graduation_cap', 'mortar_board']),
new Emoji("🧢", "Objects", ['billed_cap']),
new Emoji("🪖", "Objects", ['military_helmet']),
new Emoji("⛑️", "Objects", ['helmet_with_cross', 'rescue_worker_helmet']),
new Emoji("📿", "Objects", ['prayer_beads']),
new Emoji("💄", "Objects", ['lipstick']),
new Emoji("💍", "Objects", ['ring']),
new Emoji("💎", "Objects", ['gem']),
new Emoji("🔇", "Objects", ['mute', 'no_sound']),
new Emoji("🔈️", "Objects", ['low_volume', 'quiet_sound', 'speaker']),
new Emoji("🔉", "Objects", ['medium_volumne', 'sound']),
new Emoji("🔊", "Objects", ['high_volume', 'loud_sound']),
new Emoji("📢", "Objects", ['loudspeaker']),
new Emoji("📣", "Objects", ['mega', 'megaphone']),
new Emoji("📯", "Objects", ['postal_horn']),
new Emoji("🔔", "Objects", ['bell']),
new Emoji("🔕", "Objects", ['no_bell']),
new Emoji("🎼", "Objects", ['musical_score']),
new Emoji("🎵", "Objects", ['musical_note']),
new Emoji("🎶", "Objects", ['musical_notes', 'notes']),
new Emoji("🎙️", "Objects", ['studio_microphone']),
new Emoji("🎚️", "Objects", ['level_slider']),
new Emoji("🎛️", "Objects", ['control_knobs']),
new Emoji("🎤", "Objects", ['microphone']),
new Emoji("🎧️", "Objects", ['headphones']),
new Emoji("📻️", "Objects", ['radio']),
new Emoji("🎷", "Objects", ['saxophone']),
new Emoji("🪗", "Objects", ['accordion']),
new Emoji("🎸", "Objects", ['guitar']),
new Emoji("🎹", "Objects", ['musical_keyboard']),
new Emoji("🎺", "Objects", ['trumpet']),
new Emoji("🎻", "Objects", ['violin']),
new Emoji("🪕", "Objects", ['banjo']),
new Emoji("🥁", "Objects", ['drum']),
new Emoji("🪘", "Objects", ['long_drum']),
new Emoji("📱", "Objects", ['android', 'iphone', 'mobile_phone']),
new Emoji("📲", "Objects", ['calling', 'mobile_phone_arrow']),
new Emoji("☎️", "Objects", ['telephone']),
new Emoji("📞", "Objects", ['telephone_receiver']),
new Emoji("📟️", "Objects", ['pager']),
new Emoji("📠", "Objects", ['fax', 'fax_machine']),
new Emoji("🔋", "Objects", ['battery']),
new Emoji("🪫", "Objects", ['low_battery']),
new Emoji("🔌", "Objects", ['electric_plug']),
new Emoji("💻️", "Objects", ['laptop']),
new Emoji("🖥️", "Objects", ['computer', 'desktop_computer']),
new Emoji("🖨️", "Objects", ['printer']),
new Emoji("⌨️", "Objects", ['keyboard']),
new Emoji("🖱️", "Objects", ['computer_mouse']),
new Emoji("🖲️", "Objects", ['trackball']),
new Emoji("💽", "Objects", ['computer_disk', 'minidisc']),
new Emoji("💾", "Objects", ['floppy_disk']),
new Emoji("💿️", "Objects", ['cd', 'optical_disk']),
new Emoji("📀", "Objects", ['dvd']),
new Emoji("🧮", "Objects", ['abacus']),
new Emoji("🎥", "Objects", ['movie_camera']),
new Emoji("🎞️", "Objects", ['film_frames']),
new Emoji("📽️", "Objects", ['film_projector']),
new Emoji("🎬️", "Objects", ['clapper']),
new Emoji("📺️", "Objects", ['tv']),
new Emoji("📷️", "Objects", ['camera']),
new Emoji("📸", "Objects", ['camera_with_flash']),
new Emoji("📹️", "Objects", ['video_camera']),
new Emoji("📼", "Objects", ['vhs', 'videocassette']),
new Emoji("🔍️", "Objects", ['mag']),
new Emoji("🔎", "Objects", ['mag_right']),
new Emoji("🕯️", "Objects", ['candle']),
new Emoji("💡", "Objects", ['bulb', 'light_bulb']),
new Emoji("🔦", "Objects", ['flashlight']),
new Emoji("🏮", "Objects", ['izakaya_lantern', 'red_paper_lantern']),
new Emoji("🪔", "Objects", ['diya_lamp']),
new Emoji("📔", "Objects", ['notebook_with_decorative_cover']),
new Emoji("📕", "Objects", ['closed_book']),
new Emoji("📖", "Objects", ['book', 'open_book']),
new Emoji("📗", "Objects", ['green_book']),
new Emoji("📘", "Objects", ['blue_book']),
new Emoji("📙", "Objects", ['orange_book']),
new Emoji("📚️", "Objects", ['books']),
new Emoji("📓", "Objects", ['notebook']),
new Emoji("📒", "Objects", ['ledger']),
new Emoji("📃", "Objects", ['page_with_curl']),
new Emoji("📜", "Objects", ['scroll']),
new Emoji("📄", "Objects", ['page_facing_up']),
new Emoji("📰", "Objects", ['newspaper']),
new Emoji("🗞️", "Objects", ['rolled_up_newspaper']),
new Emoji("📑", "Objects", ['bookmark_tabs']),
new Emoji("🔖", "Objects", ['bookmark']),
new Emoji("🏷️", "Objects", ['label']),
new Emoji("💰️", "Objects", ['moneybag']),
new Emoji("🪙", "Objects", ['coin']),
new Emoji("💴", "Objects", ['yen']),
new Emoji("💵", "Objects", ['dollar']),
new Emoji("💶", "Objects", ['euro']),
new Emoji("💷", "Objects", ['pound']),
new Emoji("💸", "Objects", ['money_with_wings']),
new Emoji("💳️", "Objects", ['credit_card']),
new Emoji("🧾", "Objects", ['receipt']),
new Emoji("💹", "Objects", ['chart']),
new Emoji("✉️", "Objects", ['envelope']),
new Emoji("📧", "Objects", ['e-mail', 'email']),
new Emoji("📨", "Objects", ['incoming_envelope']),
new Emoji("📩", "Objects", ['envelope_with_arrow']),
new Emoji("📤️", "Objects", ['outbox_tray']),
new Emoji("📥️", "Objects", ['inbox_tray']),
new Emoji("📦️", "Objects", ['package']),
new Emoji("📫️", "Objects", ['mailbox']),
new Emoji("📪️", "Objects", ['mailbox_closed']),
new Emoji("📬️", "Objects", ['mailbox_with_mail']),
new Emoji("📭️", "Objects", ['mailbox_with_no_mail']),
new Emoji("📮", "Objects", ['postbox']),
new Emoji("🗳️", "Objects", ['ballot_box']),
new Emoji("✏️", "Objects", ['pencil']),
new Emoji("✒️", "Objects", ['black_nib']),
new Emoji("🖋️", "Objects", ['fountain_pen']),
new Emoji("🖊️", "Objects", ['pen']),
new Emoji("🖌️", "Objects", ['paintbrush']),
new Emoji("🖍️", "Objects", ['crayon']),
new Emoji("📝", "Objects", ['memo']),
new Emoji("💼", "Objects", ['briefcase']),
new Emoji("📁", "Objects", ['file_folder']),
new Emoji("📂", "Objects", ['open_file_folder']),
new Emoji("🗂️", "Objects", ['card_index_dividers']),
new Emoji("📅", "Objects", ['date']),
new Emoji("📆", "Objects", ['calendar']),
new Emoji("🗒️", "Objects", ['notepad_spiral']),
new Emoji("🗓️", "Objects", ['calendar_spiral']),
new Emoji("📇", "Objects", ['card_index']),
new Emoji("📈", "Objects", ['chart_increasing', 'chart_with_upwards_trend']),
new Emoji("📉", "Objects", ['chart_decreasing', 'chart_with_downwards_trend']),
new Emoji("📊", "Objects", ['bar_chart']),
new Emoji("📋️", "Objects", ['clipboard']),
new Emoji("📌", "Objects", ['pushpin']),
new Emoji("📍", "Objects", ['round_pushpin']),
new Emoji("📎", "Objects", ['paperclip']),
new Emoji("🖇️", "Objects", ['paperclips']),
new Emoji("📏", "Objects", ['straight_ruler']),
new Emoji("📐", "Objects", ['triangular_ruler']),
new Emoji("✂️", "Objects", ['scissors']),
new Emoji("🗃️", "Objects", ['card_file_box']),
new Emoji("🗄️", "Objects", ['file_cabinet']),
new Emoji("🗑️", "Objects", ['trashcan', 'wastebasket']),
new Emoji("🔒️", "Objects", ['lock', 'locked']),
new Emoji("🔓️", "Objects", ['unlock', 'unlocked']),
new Emoji("🔏", "Objects", ['lock_with_ink_pen', 'locked_with_pen']),
new Emoji("🔐", "Objects", ['closed_lock_with_key', 'locked_with_key']),
new Emoji("🔑", "Objects", ['key']),
new Emoji("🗝️", "Objects", ['old_key']),
new Emoji("🔨", "Objects", ['hammer']),
new Emoji("🪓", "Objects", ['axe']),
new Emoji("⛏️", "Objects", ['pick']),
new Emoji("⚒️", "Objects", ['hammer_and_pick']),
new Emoji("🛠️", "Objects", ['hammer_and_wrench']),
new Emoji("🗡️", "Objects", ['dagger']),
new Emoji("⚔️", "Objects", ['crossed_swords']),
new Emoji("🔫", "Objects", ['gun', 'pistol']),
new Emoji("🪃", "Objects", ['boomerang']),
new Emoji("🏹", "Objects", ['bow_and_arrow']),
new Emoji("🛡️", "Objects", ['shield']),
new Emoji("🪚", "Objects", ['carpentry_saw']),
new Emoji("🔧", "Objects", ['wrench']),
new Emoji("🪛", "Objects", ['screwdriver']),
new Emoji("🔩", "Objects", ['nut_and_bolt']),
new Emoji("⚙️", "Objects", ['gear']),
new Emoji("🗜️", "Objects", ['clamp', 'compression']),
new Emoji("⚖️", "Objects", ['scales']),
new Emoji("🦯", "Objects", ['probing_cane', 'white_cane']),
new Emoji("🔗", "Objects", ['link']),
new Emoji("⛓️", "Objects", ['chains']),
new Emoji("🪝", "Objects", ['hook']),
new Emoji("🧰", "Objects", ['toolbox']),
new Emoji("🧲", "Objects", ['magnet']),
new Emoji("🪜", "Objects", ['ladder']),
new Emoji("⚗️", "Objects", ['alembic']),
new Emoji("🧪", "Objects", ['test_tube']),
new Emoji("🧫", "Objects", ['petri_dish']),
new Emoji("🧬", "Objects", ['dna', 'double_helix']),
new Emoji("🔬", "Objects", ['microscope']),
new Emoji("🔭", "Objects", ['telescope']),
new Emoji("📡", "Objects", ['satellite_antenna']),
new Emoji("💉", "Objects", ['syringe']),
new Emoji("🩸", "Objects", ['drop_of_blood']),
new Emoji("💊", "Objects", ['pill']),
new Emoji("🩹", "Objects", ['adhesive_bandage', 'bandaid']),
new Emoji("🩼", "Objects", ['crutch']),
new Emoji("🩺", "Objects", ['stethoscope']),
new Emoji("🩻", "Objects", ['x-ray', 'xray']),
new Emoji("🚪", "Objects", ['door']),
new Emoji("🛗", "Objects", ['elevator']),
new Emoji("🪞", "Objects", ['mirror']),
new Emoji("🪟", "Objects", ['window']),
new Emoji("🛏️", "Objects", ['bed']),
new Emoji("🛋️", "Objects", ['couch_and_lamp']),
new Emoji("🪑", "Objects", ['chair']),
new Emoji("🚽", "Objects", ['toilet']),
new Emoji("🪠", "Objects", ['plunger']),
new Emoji("🚿", "Objects", ['shower']),
new Emoji("🛁", "Objects", ['bathtub']),
new Emoji("🪤", "Objects", ['mouse_trap']),
new Emoji("🪒", "Objects", ['razor']),
new Emoji("🧴", "Objects", ['lotion_bottle']),
new Emoji("🧷", "Objects", ['safety_pin']),
new Emoji("🧹", "Objects", ['broom']),
new Emoji("🧺", "Objects", ['basket']),
new Emoji("🧻", "Objects", ['roll_of_paper', 'toilet_paper']),
new Emoji("🪣", "Objects", ['bucket']),
new Emoji("🧼", "Objects", ['soap']),
new Emoji("🫧", "Objects", ['bubbles']),
new Emoji("🪥", "Objects", ['toothbrush']),
new Emoji("🧽", "Objects", ['sponge']),
new Emoji("🧯", "Objects", ['fire_extinguisher']),
new Emoji("🛒", "Objects", ['shopping_cart']),
new Emoji("🚬", "Objects", ['cigarette', 'smoking']),
new Emoji("⚰️", "Objects", ['coffin']),
new Emoji("🪦", "Objects", ['headstone']),
new Emoji("⚱️", "Objects", ['funeral_urn']),
new Emoji("🗿", "Objects", ['moai', 'moyai']),
new Emoji("🪧", "Objects", ['placard']),
new Emoji("🪪", "Objects", ['id_card']),
new Emoji("🏧", "Symbols", ['atm']),
new Emoji("🚮", "Symbols", ['litter_bin', 'put_litter_in_its_place']),
new Emoji("🚰", "Symbols", ['potable_water']),
new Emoji("♿️", "Symbols", ['handicapped', 'wheelchair']),
new Emoji("🚹️", "Symbols", ['mens']),
new Emoji("🚺️", "Symbols", ['womens']),
new Emoji("🚻", "Symbols", ['bathroom', 'restroom']),
new Emoji("🚼️", "Symbols", ['baby_symbol']),
new Emoji("🚾", "Symbols", ['water_closet', 'wc']),
new Emoji("🛂", "Symbols", ['passport_control']),
new Emoji("🛃", "Symbols", ['customs']),
new Emoji("🛄", "Symbols", ['baggage_claim']),
new Emoji("🛅", "Symbols", ['left_luggage']),
new Emoji("⚠️", "Symbols", ['warning']),
new Emoji("🚸", "Symbols", ['children_crossing']),
new Emoji("⛔️", "Symbols", ['no_entry']),
new Emoji("🚫", "Symbols", ['no_entry_sign']),
new Emoji("🚳", "Symbols", ['no_bicycles']),
new Emoji("🚭️", "Symbols", ['no_smoking']),
new Emoji("🚯", "Symbols", ['do_not_litter', 'no_littering']),
new Emoji("🚱", "Symbols", ['non-potable_water']),
new Emoji("🚷", "Symbols", ['no_pedestrians']),
new Emoji("📵", "Symbols", ['no_mobile_phones']),
new Emoji("🔞", "Symbols", ['no_one_under_18', 'underage']),
new Emoji("☢️", "Symbols", ['radioactive']),
new Emoji("☣️", "Symbols", ['biohazard']),
new Emoji("⬆️", "Symbols", ['arrow_up']),
new Emoji("↗️", "Symbols", ['arrow_upper_right']),
new Emoji("➡️", "Symbols", ['arrow_right']),
new Emoji("↘️", "Symbols", ['arrow_lower_right']),
new Emoji("⬇️", "Symbols", ['arrow_down']),
new Emoji("↙️", "Symbols", ['arrow_lower_left']),
new Emoji("⬅️", "Symbols", ['arrow_left']),
new Emoji("↖️", "Symbols", ['arrow_upper_left']),
new Emoji("↕️", "Symbols", ['arrow_up_down']),
new Emoji("↔️", "Symbols", ['left_right_arrow']),
new Emoji("↩️", "Symbols", ['arrow_left_hook', 'leftwards_arrow_with_hook']),
new Emoji("↪️", "Symbols", ['arrow_right_hook', 'rightwards_arrow_with_hook']),
new Emoji("⤴️", "Symbols", ['arrow_heading_up']),
new Emoji("⤵️", "Symbols", ['arrow_heading_down']),
new Emoji("🔃", "Symbols", ['arrows_clockwise', 'clockwise']),
new Emoji("🔄", "Symbols", ['arrows_counterclockwise', 'counterclockwise']),
new Emoji("🔙", "Symbols", ['back']),
new Emoji("🔚", "Symbols", ['end']),
new Emoji("🔛", "Symbols", ['on']),
new Emoji("🔜", "Symbols", ['soon']),
new Emoji("🔝", "Symbols", ['top']),
new Emoji("🛐", "Symbols", ['place_of_worship']),
new Emoji("⚛️", "Symbols", ['atom', 'atom_symbol']),
new Emoji("🕉️", "Symbols", ['om']),
new Emoji("✡️", "Symbols", ['star_of_david']),
new Emoji("☸️", "Symbols", ['wheel_of_dharma']),
new Emoji("☯️", "Symbols", ['yin_yang']),
new Emoji("✝️", "Symbols", ['latin_cross']),
new Emoji("☦️", "Symbols", ['orthodox_cross']),
new Emoji("☪️", "Symbols", ['star_and_crescent']),
new Emoji("☮️", "Symbols", ['peace', 'peace_symbol']),
new Emoji("🕎", "Symbols", ['menorah']),
new Emoji("🔯", "Symbols", ['six_pointed_star']),
new Emoji("♈️", "Symbols", ['aries']),
new Emoji("♉️", "Symbols", ['taurus']),
new Emoji("♊️", "Symbols", ['gemini']),
new Emoji("♋️", "Symbols", ['cancer']),
new Emoji("♌️", "Symbols", ['leo']),
new Emoji("♍️", "Symbols", ['virgo']),
new Emoji("♎️", "Symbols", ['libra']),
new Emoji("♏️", "Symbols", ['scorpius']),
new Emoji("♐️", "Symbols", ['sagittarius']),
new Emoji("♑️", "Symbols", ['capricorn']),
new Emoji("♒️", "Symbols", ['aquarius']),
new Emoji("♓️", "Symbols", ['pisces']),
new Emoji("⛎", "Symbols", ['ophiuchus']),
new Emoji("🔀", "Symbols", ['shuffle', 'twisted_rightwards_arrows']),
new Emoji("🔁", "Symbols", ['repeat']),
new Emoji("🔂", "Symbols", ['repeat_one']),
new Emoji("▶️", "Symbols", ['arrow_forward', 'play']),
new Emoji("⏩️", "Symbols", ['fast_forward']),
new Emoji("⏭️", "Symbols", ['next_track']),
new Emoji("⏯️", "Symbols", ['play_pause']),
new Emoji("◀️", "Symbols", ['arrow_backward', 'reverse']),
new Emoji("⏪️", "Symbols", ['fast_reverse', 'rewind']),
new Emoji("⏮️", "Symbols", ['previous_track']),
new Emoji("🔼", "Symbols", ['arrow_up_small', 'up']),
new Emoji("⏫", "Symbols", ['arrow_double_up', 'fast_up']),
new Emoji("🔽", "Symbols", ['arrow_down_small', 'down']),
new Emoji("⏬", "Symbols", ['arrow_double_down', 'fast_down']),
new Emoji("⏸️", "Symbols", ['pause']),
new Emoji("⏹️", "Symbols", ['stop']),
new Emoji("⏺️", "Symbols", ['record']),
new Emoji("⏏️", "Symbols", ['eject']),
new Emoji("🎦", "Symbols", ['cinema']),
new Emoji("🔅", "Symbols", ['dim_button', 'low_brightness']),
new Emoji("🔆", "Symbols", ['bright_button', 'high_brightness']),
new Emoji("📶", "Symbols", ['antenna_bars', 'signal_strength']),
new Emoji("📳", "Symbols", ['vibration_mode']),
new Emoji("📴", "Symbols", ['mobile_phone_off']),
new Emoji("♀️", "Symbols", ['female', 'female_sign']),
new Emoji("♂️", "Symbols", ['male', 'male_sign']),
new Emoji("⚧️", "Symbols", ['transgender_symbol']),
new Emoji("✖️", "Symbols", ['multiplication', 'multiply']),
new Emoji("➕", "Symbols", ['plus']),
new Emoji("➖", "Symbols", ['minus']),
new Emoji("➗", "Symbols", ['divide', 'division']),
new Emoji("🟰", "Symbols", ['heavy_equals_sign']),
new Emoji("♾️", "Symbols", ['infinity']),
new Emoji("‼️", "Symbols", ['bangbang', 'double_exclamation']),
new Emoji("⁉️", "Symbols", ['exclamation_question', 'interrobang']),
new Emoji("❓️", "Symbols", ['question']),
new Emoji("❔", "Symbols", ['white_question']),
new Emoji("❕", "Symbols", ['white_exclamation']),
new Emoji("❗️", "Symbols", ['exclamation']),
new Emoji("〰️", "Symbols", ['wavy_dash']),
new Emoji("💱", "Symbols", ['currency_exchange']),
new Emoji("💲", "Symbols", ['heavy_dollar_sign']),
new Emoji("⚕️", "Symbols", ['medical', 'medical_symbol']),
new Emoji("♻️", "Symbols", ['recycle', 'recycling_symbol']),
new Emoji("⚜️", "Symbols", ['fleur-de-lis']),
new Emoji("🔱", "Symbols", ['trident']),
new Emoji("📛", "Symbols", ['name_badge']),
new Emoji("🔰", "Symbols", ['beginner']),
new Emoji("⭕️", "Symbols", ['hollow_red_circle', 'red_o']),
new Emoji("✅", "Symbols", ['check_mark_button', 'white_check_mark']),
new Emoji("☑️", "Symbols", ['ballot_box_with_check']),
new Emoji("✔️", "Symbols", ['check_mark', 'heavy_check_mark']),
new Emoji("❌", "Symbols", ['cross_mark', 'x']),
new Emoji("❎", "Symbols", ['cross_mark_button', 'negative_squared_cross_mark']),
new Emoji("➰", "Symbols", ['curly_loop']),
new Emoji("➿", "Symbols", ['double_curly_loop', 'loop']),
new Emoji("〽️", "Symbols", ['part_alternation_mark']),
new Emoji("✳️", "Symbols", ['eight_spoked_asterisk']),
new Emoji("✴️", "Symbols", ['eight_pointed_black_star']),
new Emoji("❇️", "Symbols", ['sparkle']),
new Emoji("©️", "Symbols", ['copyright']),
new Emoji("®️", "Symbols", ['registered']),
new Emoji("™️", "Symbols", ['tm', 'trade_mark']),
new Emoji("#️⃣", "Symbols", ['hash', 'number_sign']),
new Emoji("*️⃣", "Symbols", ['asterisk']),
new Emoji("0️⃣", "Symbols", ['zero']),
new Emoji("1️⃣", "Symbols", ['one']),
new Emoji("2️⃣", "Symbols", ['two']),
new Emoji("3️⃣", "Symbols", ['three']),
new Emoji("4️⃣", "Symbols", ['four']),
new Emoji("5️⃣", "Symbols", ['five']),
new Emoji("6️⃣", "Symbols", ['six']),
new Emoji("7️⃣", "Symbols", ['seven']),
new Emoji("8️⃣", "Symbols", ['eight']),
new Emoji("9️⃣", "Symbols", ['nine']),
new Emoji("🔟", "Symbols", ['ten']),
new Emoji("🔠", "Symbols", ['capital_abcd']),
new Emoji("🔡", "Symbols", ['abcd']),
new Emoji("🔢", "Symbols", ['1234']),
new Emoji("🔣", "Symbols", ['symbols']),
new Emoji("🔤", "Symbols", ['abc']),
new Emoji("🅰️", "Symbols", ['a', 'a_blood']),
new Emoji("🆎", "Symbols", ['ab', 'ab_blood']),
new Emoji("🅱️", "Symbols", ['b', 'b_blood']),
new Emoji("🆑", "Symbols", ['cl']),
new Emoji("🆒", "Symbols", ['cool']),
new Emoji("🆓", "Symbols", ['free']),
new Emoji("ℹ️", "Symbols", ['info', 'information_source']),
new Emoji("🆔", "Symbols", ['id']),
new Emoji("Ⓜ️", "Symbols", ['m']),
new Emoji("🆕", "Symbols", ['new']),
new Emoji("🆖", "Symbols", ['ng']),
new Emoji("🅾️", "Symbols", ['o', 'o_blood']),
new Emoji("🆗", "Symbols", ['ok']),
new Emoji("🅿️", "Symbols", ['parking']),
new Emoji("🆘", "Symbols", ['sos']),
new Emoji("🆙", "Symbols", ['up2']),
new Emoji("🆚", "Symbols", ['vs']),
new Emoji("🈁", "Symbols", ['ja_here', 'koko']),
new Emoji("🈂️", "Symbols", ['ja_service_charge']),
new Emoji("🈷️", "Symbols", ['ja_monthly_amount']),
new Emoji("🈶", "Symbols", ['ja_not_free_of_carge']),
new Emoji("🈯️", "Symbols", ['ja_reserved']),
new Emoji("🉐", "Symbols", ['ideograph_advantage', 'ja_bargain']),
new Emoji("🈹", "Symbols", ['ja_discount']),
new Emoji("🈚️", "Symbols", ['ja_free_of_charge']),
new Emoji("🈲", "Symbols", ['ja_prohibited']),
new Emoji("🉑", "Symbols", ['accept', 'ja_acceptable']),
new Emoji("🈸", "Symbols", ['ja_application']),
new Emoji("🈴", "Symbols", ['ja_passing_grade']),
new Emoji("🈳", "Symbols", ['ja_vacancy']),
new Emoji("㊗️", "Symbols", ['congratulations', 'ja_congratulations']),
new Emoji("㊙️", "Symbols", ['ja_secret', 'secret']),
new Emoji("🈺", "Symbols", ['ja_open_for_business']),
new Emoji("🈵", "Symbols", ['ja_no_vacancy']),
new Emoji("🔴", "Symbols", ['red_circle']),
new Emoji("🟠", "Symbols", ['orange_circle']),
new Emoji("🟡", "Symbols", ['yellow_circle']),
new Emoji("🟢", "Symbols", ['green_circle']),
new Emoji("🔵", "Symbols", ['blue_circle']),
new Emoji("🟣", "Symbols", ['purple_circle']),
new Emoji("🟤", "Symbols", ['brown_circle']),
new Emoji("⚫️", "Symbols", ['black_circle']),
new Emoji("⚪️", "Symbols", ['white_circle']),
new Emoji("🟥", "Symbols", ['red_square']),
new Emoji("🟧", "Symbols", ['orange_square']),
new Emoji("🟨", "Symbols", ['yellow_square']),
new Emoji("🟩", "Symbols", ['green_square']),
new Emoji("🟦", "Symbols", ['blue_square']),
new Emoji("🟪", "Symbols", ['purple_square']),
new Emoji("🟫", "Symbols", ['brown_square']),
new Emoji("⬛️", "Symbols", ['black_large_square']),
new Emoji("⬜️", "Symbols", ['white_large_square']),
new Emoji("◼️", "Symbols", ['black_medium_square']),
new Emoji("◻️", "Symbols", ['white_medium_square']),
new Emoji("◾️", "Symbols", ['black_medium_small_square']),
new Emoji("◽️", "Symbols", ['white_medium_small_square']),
new Emoji("▪️", "Symbols", ['black_small_square']),
new Emoji("▫️", "Symbols", ['white_small_square']),
new Emoji("🔶", "Symbols", ['large_orange_diamond']),
new Emoji("🔷", "Symbols", ['large_blue_diamond']),
new Emoji("🔸", "Symbols", ['small_orange_diamond']),
new Emoji("🔹", "Symbols", ['small_blue_diamond']),
new Emoji("🔺", "Symbols", ['small_red_triangle']),
new Emoji("🔻", "Symbols", ['small_red_triangle_down']),
new Emoji("💠", "Symbols", ['diamond_shape_with_a_dot_inside', 'diamond_with_a_dot']),
new Emoji("🔘", "Symbols", ['radio_button']),
new Emoji("🔳", "Symbols", ['white_square_button']),
new Emoji("🔲", "Symbols", ['black_square_button']),
new Emoji("🏁", "Flags", ['checkered_flag']),
new Emoji("🚩", "Flags", ['triangular_flag', 'triangular_flag_on_post']),
new Emoji("🎌", "Flags", ['crossed_flags']),
new Emoji("🏴", "Flags", ['black_flag']),
new Emoji("🏳️", "Flags", ['white_flag']),
new Emoji("🏳️‍🌈", "Flags", ['rainbow_flag']),
new Emoji("🏳️‍⚧️", "Flags", ['transgender_flag']),
new Emoji("🏴‍☠️", "Flags", ['jolly_roger', 'pirate_flag']),
new Emoji("🇦🇨", "Flags", ['ascension_island', 'flag_ac']),
new Emoji("🇦🇩", "Flags", ['andorra', 'flag_ad']),
new Emoji("🇦🇪", "Flags", ['flag_ae', 'united_arab_emirates']),
new Emoji("🇦🇫", "Flags", ['afghanistan', 'flag_af']),
new Emoji("🇦🇬", "Flags", ['antigua_barbuda', 'flag_ag']),
new Emoji("🇦🇮", "Flags", ['anguilla', 'flag_ai']),
new Emoji("🇦🇱", "Flags", ['albania', 'flag_al']),
new Emoji("🇦🇲", "Flags", ['armenia', 'flag_am']),
new Emoji("🇦🇴", "Flags", ['angola', 'flag_ao']),
new Emoji("🇦🇶", "Flags", ['antarctica', 'flag_aq']),
new Emoji("🇦🇷", "Flags", ['argentina', 'flag_ar']),
new Emoji("🇦🇸", "Flags", ['american_samoa', 'flag_as']),
new Emoji("🇦🇹", "Flags", ['austria', 'flag_at']),
new Emoji("🇦🇺", "Flags", ['australia', 'flag_au']),
new Emoji("🇦🇼", "Flags", ['aruba', 'flag_aw']),
new Emoji("🇦🇽", "Flags", ['aland_islands', 'flag_ax']),
new Emoji("🇦🇿", "Flags", ['azerbaijan', 'flag_az']),
new Emoji("🇧🇦", "Flags", ['bosnia_herzegovina', 'flag_ba']),
new Emoji("🇧🇧", "Flags", ['barbados', 'flag_bb']),
new Emoji("🇧🇩", "Flags", ['bangladesh', 'flag_bd']),
new Emoji("🇧🇪", "Flags", ['belgium', 'flag_be']),
new Emoji("🇧🇫", "Flags", ['burkina_faso', 'flag_bf']),
new Emoji("🇧🇬", "Flags", ['bulgaria', 'flag_bg']),
new Emoji("🇧🇭", "Flags", ['bahrain', 'flag_bh']),
new Emoji("🇧🇮", "Flags", ['burundi', 'flag_bi']),
new Emoji("🇧🇯", "Flags", ['benin', 'flag_bj']),
new Emoji("🇧🇱", "Flags", ['flag_bl', 'st_barthelemy']),
new Emoji("🇧🇲", "Flags", ['bermuda', 'flag_bm']),
new Emoji("🇧🇳", "Flags", ['brunei', 'flag_bn']),
new Emoji("🇧🇴", "Flags", ['bolivia', 'flag_bo']),
new Emoji("🇧🇶", "Flags", ['caribbean_netherlands', 'flag_bq']),
new Emoji("🇧🇷", "Flags", ['brazil', 'flag_br']),
new Emoji("🇧🇸", "Flags", ['bahamas', 'flag_bs']),
new Emoji("🇧🇹", "Flags", ['bhutan', 'flag_bt']),
new Emoji("🇧🇻", "Flags", ['bouvet_island', 'flag_bv']),
new Emoji("🇧🇼", "Flags", ['botswana', 'flag_bw']),
new Emoji("🇧🇾", "Flags", ['belarus', 'flag_by']),
new Emoji("🇧🇿", "Flags", ['belize', 'flag_bz']),
new Emoji("🇨🇦", "Flags", ['canada', 'flag_ca']),
new Emoji("🇨🇨", "Flags", ['cocos_islands', 'flag_cc']),
new Emoji("🇨🇩", "Flags", ['congo_kinshasa', 'flag_cd']),
new Emoji("🇨🇫", "Flags", ['central_african_republic', 'flag_cf']),
new Emoji("🇨🇬", "Flags", ['congo_brazzaville', 'flag_cg']),
new Emoji("🇨🇭", "Flags", ['flag_ch', 'switzerland']),
new Emoji("🇨🇮", "Flags", ['cote_divoire', 'flag_ci']),
new Emoji("🇨🇰", "Flags", ['cook_islands', 'flag_ck']),
new Emoji("🇨🇱", "Flags", ['chile', 'flag_cl']),
new Emoji("🇨🇲", "Flags", ['cameroon', 'flag_cm']),
new Emoji("🇨🇳", "Flags", ['china', 'flag_cn']),
new Emoji("🇨🇴", "Flags", ['colombia', 'flag_co']),
new Emoji("🇨🇵", "Flags", ['clipperton_island', 'flag_cp']),
new Emoji("🇨🇷", "Flags", ['costa_rica', 'flag_cr']),
new Emoji("🇨🇺", "Flags", ['cuba', 'flag_cu']),
new Emoji("🇨🇻", "Flags", ['cape_verde', 'flag_cv']),
new Emoji("🇨🇼", "Flags", ['curacao', 'flag_cw']),
new Emoji("🇨🇽", "Flags", ['christmas_island', 'flag_cx']),
new Emoji("🇨🇾", "Flags", ['cyprus', 'flag_cy']),
new Emoji("🇨🇿", "Flags", ['czech_republic', 'czechia', 'flag_cz']),
new Emoji("🇩🇪", "Flags", ['flag_de', 'germany']),
new Emoji("🇩🇬", "Flags", ['diego_garcia', 'flag_dg']),
new Emoji("🇩🇯", "Flags", ['djibouti', 'flag_dj']),
new Emoji("🇩🇰", "Flags", ['denmark', 'flag_dk']),
new Emoji("🇩🇲", "Flags", ['dominica', 'flag_dm']),
new Emoji("🇩🇴", "Flags", ['dominican_republic', 'flag_do']),
new Emoji("🇩🇿", "Flags", ['algeria', 'flag_dz']),
new Emoji("🇪🇦", "Flags", ['ceuta_melilla', 'flag_ea']),
new Emoji("🇪🇨", "Flags", ['ecuador', 'flag_ec']),
new Emoji("🇪🇪", "Flags", ['estonia', 'flag_ee']),
new Emoji("🇪🇬", "Flags", ['egypt', 'flag_eg']),
new Emoji("🇪🇭", "Flags", ['flag_eh', 'western_sahara']),
new Emoji("🇪🇷", "Flags", ['eritrea', 'flag_er']),
new Emoji("🇪🇸", "Flags", ['flag_es', 'spain']),
new Emoji("🇪🇹", "Flags", ['ethiopia', 'flag_et']),
new Emoji("🇪🇺", "Flags", ['european_union', 'flag_eu']),
new Emoji("🇫🇮", "Flags", ['finland', 'flag_fi']),
new Emoji("🇫🇯", "Flags", ['fiji', 'flag_fj']),
new Emoji("🇫🇰", "Flags", ['falkland_islands', 'flag_fk']),
new Emoji("🇫🇲", "Flags", ['flag_fm', 'micronesia']),
new Emoji("🇫🇴", "Flags", ['faroe_islands', 'flag_fo']),
new Emoji("🇫🇷", "Flags", ['flag_fr', 'france']),
new Emoji("🇬🇦", "Flags", ['flag_ga', 'gabon']),
new Emoji("🇬🇧", "Flags", ['flag_gb', 'uk', 'united_kingdom']),
new Emoji("🇬🇩", "Flags", ['flag_gd', 'grenada']),
new Emoji("🇬🇪", "Flags", ['flag_ge', 'georgia']),
new Emoji("🇬🇫", "Flags", ['flag_gf', 'french_guiana']),
new Emoji("🇬🇬", "Flags", ['flag_gg', 'guernsey']),
new Emoji("🇬🇭", "Flags", ['flag_gh', 'ghana']),
new Emoji("🇬🇮", "Flags", ['flag_gi', 'gibraltar']),
new Emoji("🇬🇱", "Flags", ['flag_gl', 'greenland']),
new Emoji("🇬🇲", "Flags", ['flag_gm', 'gambia']),
new Emoji("🇬🇳", "Flags", ['flag_gn', 'guinea']),
new Emoji("🇬🇵", "Flags", ['flag_gp', 'guadeloupe']),
new Emoji("🇬🇶", "Flags", ['equatorial_guinea', 'flag_gq']),
new Emoji("🇬🇷", "Flags", ['flag_gr', 'greece']),
new Emoji("🇬🇸", "Flags", ['flag_gs', 'south_georgia_south_sandwich_islands']),
new Emoji("🇬🇹", "Flags", ['flag_gt', 'guatemala']),
new Emoji("🇬🇺", "Flags", ['flag_gu', 'guam']),
new Emoji("🇬🇼", "Flags", ['flag_gw', 'guinea_bissau']),
new Emoji("🇬🇾", "Flags", ['flag_gy', 'guyana']),
new Emoji("🇭🇰", "Flags", ['flag_hk', 'hong_kong']),
new Emoji("🇭🇲", "Flags", ['flag_hm', 'heard_mcdonald_islands']),
new Emoji("🇭🇳", "Flags", ['flag_hn', 'honduras']),
new Emoji("🇭🇷", "Flags", ['croatia', 'flag_hr']),
new Emoji("🇭🇹", "Flags", ['flag_ht', 'haiti']),
new Emoji("🇭🇺", "Flags", ['flag_hu', 'hungary']),
new Emoji("🇮🇨", "Flags", ['canary_islands', 'flag_ic']),
new Emoji("🇮🇩", "Flags", ['flag_id', 'indonesia']),
new Emoji("🇮🇪", "Flags", ['flag_ie', 'ireland']),
new Emoji("🇮🇱", "Flags", ['flag_il', 'israel']),
new Emoji("🇮🇲", "Flags", ['flag_im', 'isle_of_man']),
new Emoji("🇮🇳", "Flags", ['flag_in', 'india']),
new Emoji("🇮🇴", "Flags", ['british_indian_ocean_territory', 'flag_io']),
new Emoji("🇮🇶", "Flags", ['flag_iq', 'iraq']),
new Emoji("🇮🇷", "Flags", ['flag_ir', 'iran']),
new Emoji("🇮🇸", "Flags", ['flag_is', 'iceland']),
new Emoji("🇮🇹", "Flags", ['flag_it', 'italy']),
new Emoji("🇯🇪", "Flags", ['flag_je', 'jersey']),
new Emoji("🇯🇲", "Flags", ['flag_jm', 'jamaica']),
new Emoji("🇯🇴", "Flags", ['flag_jo', 'jordan']),
new Emoji("🇯🇵", "Flags", ['flag_jp', 'japan']),
new Emoji("🇰🇪", "Flags", ['flag_ke', 'kenya']),
new Emoji("🇰🇬", "Flags", ['flag_kg', 'kyrgyzstan']),
new Emoji("🇰🇭", "Flags", ['cambodia', 'flag_kh']),
new Emoji("🇰🇮", "Flags", ['flag_ki', 'kiribati']),
new Emoji("🇰🇲", "Flags", ['comoros', 'flag_km']),
new Emoji("🇰🇳", "Flags", ['flag_kn', 'st_kitts_nevis']),
new Emoji("🇰🇵", "Flags", ['flag_kp', 'north_korea']),
new Emoji("🇰🇷", "Flags", ['flag_kr', 'south_korea']),
new Emoji("🇰🇼", "Flags", ['flag_kw', 'kuwait']),
new Emoji("🇰🇾", "Flags", ['cayman_islands', 'flag_ky']),
new Emoji("🇰🇿", "Flags", ['flag_kz', 'kazakhstan']),
new Emoji("🇱🇦", "Flags", ['flag_la', 'laos']),
new Emoji("🇱🇧", "Flags", ['flag_lb', 'lebanon']),
new Emoji("🇱🇨", "Flags", ['flag_lc', 'st_lucia']),
new Emoji("🇱🇮", "Flags", ['flag_li', 'liechtenstein']),
new Emoji("🇱🇰", "Flags", ['flag_lk', 'sri_lanka']),
new Emoji("🇱🇷", "Flags", ['flag_lr', 'liberia']),
new Emoji("🇱🇸", "Flags", ['flag_ls', 'lesotho']),
new Emoji("🇱🇹", "Flags", ['flag_lt', 'lithuania']),
new Emoji("🇱🇺", "Flags", ['flag_lu', 'luxembourg']),
new Emoji("🇱🇻", "Flags", ['flag_lv', 'latvia']),
new Emoji("🇱🇾", "Flags", ['flag_ly', 'libya']),
new Emoji("🇲🇦", "Flags", ['flag_ma', 'morocco']),
new Emoji("🇲🇨", "Flags", ['flag_mc', 'monaco']),
new Emoji("🇲🇩", "Flags", ['flag_md', 'moldova']),
new Emoji("🇲🇪", "Flags", ['flag_me', 'montenegro']),
new Emoji("🇲🇫", "Flags", ['flag_mf', 'st_martin']),
new Emoji("🇲🇬", "Flags", ['flag_mg', 'madagascar']),
new Emoji("🇲🇭", "Flags", ['flag_mh', 'marshall_islands']),
new Emoji("🇲🇰", "Flags", ['flag_mk', 'macedonia']),
new Emoji("🇲🇱", "Flags", ['flag_ml', 'mali']),
new Emoji("🇲🇲", "Flags", ['burma', 'flag_mm', 'myanmar']),
new Emoji("🇲🇳", "Flags", ['flag_mn', 'mongolia']),
new Emoji("🇲🇴", "Flags", ['flag_mo', 'macao', 'macau']),
new Emoji("🇲🇵", "Flags", ['flag_mp', 'northern_mariana_islands']),
new Emoji("🇲🇶", "Flags", ['flag_mq', 'martinique']),
new Emoji("🇲🇷", "Flags", ['flag_mr', 'mauritania']),
new Emoji("🇲🇸", "Flags", ['flag_ms', 'montserrat']),
new Emoji("🇲🇹", "Flags", ['flag_mt', 'malta']),
new Emoji("🇲🇺", "Flags", ['flag_mu', 'mauritius']),
new Emoji("🇲🇻", "Flags", ['flag_mv', 'maldives']),
new Emoji("🇲🇼", "Flags", ['flag_mw', 'malawi']),
new Emoji("🇲🇽", "Flags", ['flag_mx', 'mexico']),
new Emoji("🇲🇾", "Flags", ['flag_my', 'malaysia']),
new Emoji("🇲🇿", "Flags", ['flag_mz', 'mozambique']),
new Emoji("🇳🇦", "Flags", ['flag_na', 'namibia']),
new Emoji("🇳🇨", "Flags", ['flag_nc', 'new_caledonia']),
new Emoji("🇳🇪", "Flags", ['flag_ne', 'niger']),
new Emoji("🇳🇫", "Flags", ['flag_nf', 'norfolk_island']),
new Emoji("🇳🇬", "Flags", ['flag_ng', 'nigeria']),
new Emoji("🇳🇮", "Flags", ['flag_ni', 'nicaragua']),
new Emoji("🇳🇱", "Flags", ['flag_nl', 'netherlands']),
new Emoji("🇳🇴", "Flags", ['flag_no', 'norway']),
new Emoji("🇳🇵", "Flags", ['flag_np', 'nepal']),
new Emoji("🇳🇷", "Flags", ['flag_nr', 'nauru']),
new Emoji("🇳🇺", "Flags", ['flag_nu', 'niue']),
new Emoji("🇳🇿", "Flags", ['flag_nz', 'new_zealand']),
new Emoji("🇴🇲", "Flags", ['flag_om', 'oman']),
new Emoji("🇵🇦", "Flags", ['flag_pa', 'panama']),
new Emoji("🇵🇪", "Flags", ['flag_pe', 'peru']),
new Emoji("🇵🇫", "Flags", ['flag_pf', 'french_polynesia']),
new Emoji("🇵🇬", "Flags", ['flag_pg', 'papua_new_guinea']),
new Emoji("🇵🇭", "Flags", ['flag_ph', 'philippines']),
new Emoji("🇵🇰", "Flags", ['flag_pk', 'pakistan']),
new Emoji("🇵🇱", "Flags", ['flag_pl', 'poland']),
new Emoji("🇵🇲", "Flags", ['flag_pm', 'st_pierre_miquelon']),
new Emoji("🇵🇳", "Flags", ['flag_pn', 'pitcairn_islands']),
new Emoji("🇵🇷", "Flags", ['flag_pr', 'puerto_rico']),
new Emoji("🇵🇸", "Flags", ['flag_ps', 'palestinian_territories']),
new Emoji("🇵🇹", "Flags", ['flag_pt', 'portugal']),
new Emoji("🇵🇼", "Flags", ['flag_pw', 'palau']),
new Emoji("🇵🇾", "Flags", ['flag_py', 'paraguay']),
new Emoji("🇶🇦", "Flags", ['flag_qa', 'qatar']),
new Emoji("🇷🇪", "Flags", ['flag_re', 'reunion']),
new Emoji("🇷🇴", "Flags", ['flag_ro', 'romania']),
new Emoji("🇷🇸", "Flags", ['flag_rs', 'serbia']),
new Emoji("🇷🇺", "Flags", ['flag_ru', 'russia']),
new Emoji("🇷🇼", "Flags", ['flag_rw', 'rwanda']),
new Emoji("🇸🇦", "Flags", ['flag_sa', 'saudi_arabia']),
new Emoji("🇸🇧", "Flags", ['flag_sb', 'solomon_islands']),
new Emoji("🇸🇨", "Flags", ['flag_sc', 'seychelles']),
new Emoji("🇸🇩", "Flags", ['flag_sd', 'sudan']),
new Emoji("🇸🇪", "Flags", ['flag_se', 'sweden']),
new Emoji("🇸🇬", "Flags", ['flag_sg', 'singapore']),
new Emoji("🇸🇭", "Flags", ['flag_sh', 'st_helena']),
new Emoji("🇸🇮", "Flags", ['flag_si', 'slovenia']),
new Emoji("🇸🇯", "Flags", ['flag_sj', 'svalbard_jan_mayen']),
new Emoji("🇸🇰", "Flags", ['flag_sk', 'slovakia']),
new Emoji("🇸🇱", "Flags", ['flag_sl', 'sierra_leone']),
new Emoji("🇸🇲", "Flags", ['flag_sm', 'san_marino']),
new Emoji("🇸🇳", "Flags", ['flag_sn', 'senegal']),
new Emoji("🇸🇴", "Flags", ['flag_so', 'somalia']),
new Emoji("🇸🇷", "Flags", ['flag_sr', 'suriname']),
new Emoji("🇸🇸", "Flags", ['flag_ss', 'south_sudan']),
new Emoji("🇸🇹", "Flags", ['flag_st', 'sao_tome_principe']),
new Emoji("🇸🇻", "Flags", ['el_salvador', 'flag_sv']),
new Emoji("🇸🇽", "Flags", ['flag_sx', 'sint_maarten']),
new Emoji("🇸🇾", "Flags", ['flag_sy', 'syria']),
new Emoji("🇸🇿", "Flags", ['eswatini', 'flag_sz', 'swaziland']),
new Emoji("🇹🇦", "Flags", ['flag_ta', 'tristan_da_cunha']),
new Emoji("🇹🇨", "Flags", ['flag_tc', 'turks_caicos_islands']),
new Emoji("🇹🇩", "Flags", ['chad', 'flag_td']),
new Emoji("🇹🇫", "Flags", ['flag_tf', 'french_southern_territories']),
new Emoji("🇹🇬", "Flags", ['flag_tg', 'togo']),
new Emoji("🇹🇭", "Flags", ['flag_th', 'thailand']),
new Emoji("🇹🇯", "Flags", ['flag_tj', 'tajikistan']),
new Emoji("🇹🇰", "Flags", ['flag_tk', 'tokelau']),
new Emoji("🇹🇱", "Flags", ['flag_tl', 'timor_leste']),
new Emoji("🇹🇲", "Flags", ['flag_tm', 'turkmenistan']),
new Emoji("🇹🇳", "Flags", ['flag_tn', 'tunisia']),
new Emoji("🇹🇴", "Flags", ['flag_to', 'tonga']),
new Emoji("🇹🇷", "Flags", ['flag_tr', 'turkey_tr']),
new Emoji("🇹🇹", "Flags", ['flag_tt', 'trinidad_tobago']),
new Emoji("🇹🇻", "Flags", ['flag_tv', 'tuvalu']),
new Emoji("🇹🇼", "Flags", ['flag_tw', 'taiwan']),
new Emoji("🇹🇿", "Flags", ['flag_tz', 'tanzania']),
new Emoji("🇺🇦", "Flags", ['flag_ua', 'ukraine']),
new Emoji("🇺🇬", "Flags", ['flag_ug', 'uganda']),
new Emoji("🇺🇲", "Flags", ['flag_um', 'us_outlying_islands']),
new Emoji("🇺🇳", "Flags", ['flag_un', 'un', 'united_nations']),
new Emoji("🇺🇸", "Flags", ['flag_us', 'united_states', 'usa']),
new Emoji("🇺🇾", "Flags", ['flag_uy', 'uruguay']),
new Emoji("🇺🇿", "Flags", ['flag_uz', 'uzbekistan']),
new Emoji("🇻🇦", "Flags", ['flag_va', 'vatican_city']),
new Emoji("🇻🇨", "Flags", ['flag_vc', 'st_vincent_grenadines']),
new Emoji("🇻🇪", "Flags", ['flag_ve', 'venezuela']),
new Emoji("🇻🇬", "Flags", ['british_virgin_islands', 'flag_vg']),
new Emoji("🇻🇮", "Flags", ['flag_vi', 'us_virgin_islands']),
new Emoji("🇻🇳", "Flags", ['flag_vn', 'vietnam']),
new Emoji("🇻🇺", "Flags", ['flag_vu', 'vanuatu']),
new Emoji("🇼🇫", "Flags", ['flag_wf', 'wallis_futuna']),
new Emoji("🇼🇸", "Flags", ['flag_ws', 'samoa']),
new Emoji("🇽🇰", "Flags", ['flag_xk', 'kosovo']),
new Emoji("🇾🇪", "Flags", ['flag_ye', 'yemen']),
new Emoji("🇾🇹", "Flags", ['flag_yt', 'mayotte']),
new Emoji("🇿🇦", "Flags", ['flag_za', 'south_africa']),
new Emoji("🇿🇲", "Flags", ['flag_zm', 'zambia']),
new Emoji("🇿🇼", "Flags", ['flag_zw', 'zimbabwe']),
new Emoji("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Flags", ['england', 'flag_gbeng']),
new Emoji("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Flags", ['flag_gbsct', 'scotland']),
new Emoji("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "Flags", ['flag_gbwls', 'wales']),
]